(function(d){var f=window.AmazonUIPageJS||window.P,g=f._namespace||f.attributeErrors,c=g?g("AudibleChexCoreAssets",""):f;c.guardFatal?c.guardFatal(d)(c,window):c.execute(function(){d(c,window)})})(function(d,f,g){d.when("AudiblejQuery","ready").register("ajaxInitiator",function(c){function d(a){if("undefined"===typeof a)throw new b("No Data provided for ajax call");if("undefined"===typeof a.operation)throw new b("No method or operation provided in caller data for Ajax call ");if("undefined"===typeof a.targetDiv)throw new b("No target Div provided in caller data for Ajax call ");
if("undefined"===typeof a.url)throw new b("No url provided in caller data for Ajax call "+a.operation);if("undefined"===typeof a.dataType)throw new b("No response format provided in caller data for Ajax call "+a.operation);if("undefined"===typeof a.data)throw new b("No parameters provided in caller data for Ajax call "+a.operation);}function b(a){this.message=a;this.name="AjaxIOException"}return{initiateAjaxCall:function(a,b){try{d(a)}catch(n){console.log(n.message);return}"undefined"!==typeof b&&
"undefined"!==typeof b.preAjaxCallOperations&&b.preAjaxCallOperations(a.targetDiv);c.ajax({url:a.url,type:"POST",async:null!==a.async?a.async:!0,dataType:a.dataType,data:a.data,success:function(c){if("undefined"!==typeof b&&"undefined"!==typeof b.onAjaxSuccess)b.onAjaxSuccess(a.targetDiv,c)},error:function(c){if("undefined"!==typeof b&&"undefined"!==typeof b.onAjaxFailure)b.onAjaxFailure(a.targetDiv,c)},complete:function(c){if("undefined"!==typeof b&&"undefined"!==typeof b.onAjaxComplete)b.onAjaxComplete(a.targetDiv,
c)}})}}});"use strict";d.when("AudiblejQuery","StrictEvents","ready").register("countdownTimer",function(c,d){var b={existingCountDowns:{}},a=new d(["audibleCountdownTimerStarted","audibleCountdownTimerEnded"]);b.on=a.on.bind(a);b.off=a.off.bind(a);b._emit=a.emit.bind(a);var f=function(e,b){var a,d,f,l=c("#"+b);if(l){var h=l.data("includeSeconds")||!1;b=l.data("trimZeros")||!1;d=Math.floor(e/864E5);var m=864E5*d;a=Math.floor((e-m)/36E5);var g=36E5*a;f=0;var k=(e-m-g)/6E4;h?(h=Math.floor(k),f=Math.ceil((e-
m-g-6E4*h)/1E3),60===f&&(h++,f=0)):h=Math.ceil(k);60===h&&(a++,h=0);24===a&&(d++,a=0);e=d;d=h;k=l.data("timeFormat")||"{d}d {h}h {m}m {s}s";m=l.data("timeFormatHms")||"{h}h {m}m {s}s";g=l.data("timeFormatMs")||"{m}m {s}s";h=l.data("timeFormatS")||"{s}s";b&&("0"===e.toString()&&"0"===a.toString()&&"0"===d.toString()?k=h:"0"===e.toString()&&"0"===a.toString()?k=g:"0"===e.toString()&&(k=m));k=k.replace("{d}",e.toString()).replace("{h}",a.toString()).replace("{m}",d.toString()).replace("{s}",f.toString());
l.text(k)}else throw"Timer ID not found: "+b;},n=function(e,c){e in b.existingCountDowns?console.warn("Duplicate Timer ID detected: "+e):function(){b.existingCountDowns[e]={totalCountDown:c,elapsedMillis:0,startingTime:(new Date).getTime()};f(c,e);var d=b.existingCountDowns[e];a.emit("audibleCountdownTimerStarted",e);var g=setInterval(function(){d.elapsedMillis=(new Date).getTime()-d.startingTime;var c=d.totalCountDown-d.elapsedMillis;0>c?(clearInterval(g),f(0,e),delete b.existingCountDowns[e],a.emit("audibleCountdownTimerEnded",
e)):f(c,e)},1E3)}()};b.start=function(){c(".adbl-countdown-timer").length&&c(".adbl-countdown-timer").each(function(){var a=c(this).attr("id");if(null!==a){var b=c(this).data("duration");if(b===g)throw"Timer "+a+" does not specify a duration";n(a,b)}else throw"One or more timers do not have an id";})};b.getRemainingTime=function(a){return a in b.existingCountDowns?(a=b.existingCountDowns[a],a=a.totalCountDown-a.elapsedMillis,0<a?a:0):-1};return b})});
/* ******** */
(function(b){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,a=d?d("AudibleCloudPlayerLauncherAssets",""):c;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,c,d){b.when("AudiblejQuery","ready").register("cloudPlayerLauncher",function(a){return{openCloudPlayer:function(a,b){null!==a&&a!==d&&null!==b&&b!==d&&c.open("/webplayer?asin\x3d"+a+"\x26ref_\x3d"+b+"\x26cloudPlayerStartLoadTime\x3d"+Date.now(),"_blank2","height\x3d700,width\x3d435,resizeable\x3dno,fullscreen\x3dno,scrollbars\x3dno,toolbar\x3dno,menubar\x3dno,location\x3dno,directories\x3dno,status\x3dno").focus()}}})});
/* ******** */
