(function(g){var c=window.AmazonUIPageJS||window.P,f=c._namespace||c.attributeErrors,h=f?f("AryaAnalyticsAssets",""):c;h.guardFatal?h.guardFatal(g)(h,window):h.execute(function(){g(h,window)})})(function(g,c,f){g.when("debounce","adobeUtils").execute(function(k,d){var f=k(function(){return d.scanForImpressions(document.body)},500,2E3);["scroll","resize","click"].forEach(function(d){return c.addEventListener(d,f)});f()});g.when("debounce","boxUtility","ready").register("adobeUtils",function(k,d){function l(a){d.isInView(a,
!0,!0)&&(a.classList.remove("adbl-asin-impression"),setTimeout(function(){d.isInView(a,!0,!0)?e(a):a.classList.add("adbl-asin-impression")},2E3))}function e(a){a.classList.remove("adbl-asin-impression");a.classList.add("adbl-impression-emitted");n.push(p(a));b()}function p(a){var b=a&&a.dataset;if(!b)return{};var d=a.closest(".slot"),c=a.closest(".adbl-impression-container"),c=b.widget||c&&c.dataset.widget||d&&d.children[0].id,d=d&&d.id,m=b.url;if(!m){var e=a.closest("a");if(e&&e.href)m=e.href;else if(e=
a.querySelector('a:not([href\x3d""])'))m=e.href}var e=b.faceOut||"0",v=a.closest(".product-carousel-item");v&&(e=v.dataset.slickIndex);return{widget:c,slotId:d,url:m,faceOut:e,asin:b.asin,position:b.position===f?String(Array.prototype.indexOf.call(a.parentElement.children,a)+1):b.position,ref:m&&g(m)||r,source:b.source||"EMPTY"}}function g(a){return(a=h.exec(a))?a[1]:null}var h=/[?&\/]ref=([^&#]*)/,r=g(c.location.href);if(!c.digitalData||!c.digitalData.page||!c.digitalData.page.category)throw Error("Error initializing adobeUtils.js: missing or invalid window.digitalData object \ud83d\ude2b");
var t="DETAIL"===c.digitalData.page.category.pageType?"DETAIL":c.digitalData.page.pageInfo.pageName,u=c.digitalData.webSessionId||"",n=[],q=k(function(a){var b=1<arguments.length&&arguments[1]!==f?arguments[1]:!1;if(!(a&&a instanceof HTMLElement))throw Error("scanForAsinImpressions: called without valid element \ud83d\ude1f");b=b?e:l;a.classList.contains("adbl-asin-impression")&&b(a);Array.prototype.slice.call(a.getElementsByClassName("adbl-asin-impression")).forEach(b)}),b=k(function(){var a=c._satellite&&
c._satellite.getToolsByType("sc")[0].getS();if(!a)throw Error('Error initializing satellite "s" for Adobe analytics \ud83d\ude1f');var b=[],d={};n.forEach(function(a){var e=d[a.asin]=1+(d[a.asin]||0);(b[e-1]=b[e-1]||[]).push(a)});a.products=a.products?a.products+",":"";b.forEach(function(b){a.events=a.apl(a.events,"event181",",",1);a.products+=b.map(function(a){return";"+a.asin+";;;event181\x3d1;eVar174\x3d"+[a.asin,a.widget,a.slotId,a.position,a.faceOut,a.ref,a.source,u,t].join(".")}).join(",");
c._satellite.notify(a.products,1);a.t();a.events=a.products=""});n=[]},500);return{scanForImpressions:q}});"use strict";g.when("refMarkers","live").execute(function(k,d){var g=c.console&&console.warn&&function(d){console.warn(d)}||function(){};d("click",".adbl-ref-marker-on-click",function(d){d=this.getAttribute("data-ref-marker-feature-code");if(null===d||""===d)d=this.getAttribute("refMarkerFeatureCode"),null===d||""===d?d=f:g('"refMarkerFeatureCode" attribute is deprecated, use semantically correct "data-ref-marker-feature-code" instead');
var c=this.getAttribute("data-ref-marker-counter");if(null===c||""===c)c=this.getAttribute("refMarkerCounter"),null===c||""===c?c=f:g('"refMarkerCounter" attribute is deprecated, use semantically correct "data-ref-marker-counter" instead');k.buildAndPost(d,this,c)})});"use strict";var h="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(c){return typeof c}:function(c){return c&&"function"===typeof Symbol&&c.constructor===Symbol&&c!==Symbol.prototype?"symbol":typeof c};g.register("refMarkers",
function(){var g={top:"t",center:"c",bottom:"b",left:"l",right:"r"},d={},l=c.console&&console.warn&&function(b){console.warn(b)}||function(){},e=c.console&&console.error&&function(b){console.error(b)}||function(){};d.record=function(b){l("refMarkers.record is deprecated in favor of buildAndPost");if(0<b.length&&(b=b.data("refmarker"),0<b.length)){b="/ajax-refmarker"+b;var a=new XMLHttpRequest;a.open("GET",b,!0);a.send(b)}};d.build=function(b,a,c){if(1>arguments.length)return l("build: feature code is required."),
"";var e=["a",d.buildPageCodeFromUrl()];a&&a.nodeName&&(a=d.getSlotNameFromElement(a));"string"===typeof a&&0<a.length&&e.push(d.abbreviateSlotName(a));("string"===typeof c&&0<c.length||"number"===typeof c)&&e.push(d.abbreviate(String(c),2));e.push(d.abbreviate(b,6));return e.join("_").slice(0,32)};d.getSlotNameFromElement=function(b){for(;b;){if(b.classList.contains("slot"))return b.id;b=b.parentElement}};d.buildAndPost=function(b,a,c,e){"function"===typeof c?(e=c,c=f):"function"===typeof a&&(e=
a,a=f);b=d.build.call(f,b,a,c);d.post(b,e)};d.buildAndRecord=function(){l("refMarkers.buildAndRecord is deprecated in favor of refMarkers.buildAndPost");d.buildAndPost.apply(f,arguments)};d._getWindowPathName=function(){return c.location.pathname};var p=void 0;d._isMobile=function(){p===f&&(p=!!document.querySelector("body \x3e .adbl-page.mobile"));return p};var w=void 0,x=void 0,r=/^\/*$/;d.buildPageCodeFromUrl=function(){var b=d._getWindowPathName();x!==b&&(x=b,b=b.replace(/\/ref[^&]+/g,""),r.test(b)&&
(b="home"),d._isMobile()&&(b="m_"+b),w=b&&d.abbreviate(b,16));return w};d.post=function(b,a){if(b&&b.length){var d="/ajax-refmarker"+(-1!==b.indexOf("?ref\x3d")?"":"?ref\x3d")+b,c=new XMLHttpRequest;c.open("GET",d,!0);c.onload=function(){a&&a(!0)};c.onerror=function(){a&&a(!1);e("refMarker ["+b+"] post: error")};c.send()}else a&&a(!1),e("refMarker ["+b+"] post: invalid refMarker")};var t=/(?:_)+/,u=/^[^A-Za-z\u00C0-\u00DE\u00DF-\u024F0-9]+|[^A-Za-z\u00C0-\u00DE\u00DF-\u024F0-9]+$/g,n=/[^A-Za-z\u00C0-\u00DE\u00DF-\u024F0-9]|([a-z\u00DF-\u00FF\u0101\u0103\u0105\u0107\u0109\u010B\u010D\u010F\u0111\u0113\u0115\u0117\u0119\u011B\u011D\u011F\u0121\u0123\u0125\u0127\u0129\u012B\u012D\u012F\u0131\u0133\u0135\u0137\u0138\u013A\u013C\u013E\u0140\u0142\u0144\u0146\u0148\u0149\u014B\u014D\u014F\u0151\u0153\u0155\u0157\u0159\u015B\u015D\u015F\u0161\u0163\u0165\u0167\u0169\u016B\u016D\u016F\u0171\u0173\u0175\u0177\u017A\u017C\u017E\u017F])([A-Z\u00C0-\u00DE\u0100\u0102\u0104\u0106\u0108\u010A\u010C\u010E\u0110\u0112\u0114\u0116\u0118\u011A\u011C\u011E\u0120\u0122\u0124\u0126\u0128\u012A\u012C\u012E\u0130\u0132\u0134\u0136\u0139\u013B\u013D\u013F\u0141\u0143\u0145\u0147\u014A\u014C\u014E\u0150\u0152\u0154\u0156\u0158\u015A\u015C\u015E\u0160\u0162\u0164\u0166\u0168\u016A\u016C\u016E\u0170\u0172\u0174\u0176\u0178\u0179\u017B\u017D])|([A-Za-z\u00C0-\u00DE\u00DF-\u024F])([0-9])|([0-9])([A-Za-z\u00C0-\u00DE\u00DF-\u024F])/g,
q=/[aeiouy\u00C0\u00C1\u00C2\u00C3\u00C4\u00C5\u00C6\u00C8\u00C9\u00CA\u00CB\u00CC\u00CD\u00CE\u00CF\u00D1\u00D2\u00D3\u00D4\u00D5\u00D6\u00D8\u00D9\u00DA\u00DB\u00DC\u00DD\u00E0\u00E1\u00E2\u00E3\u00E4\u00E5\u00E6\u00E8\u00E9\u00EA\u00EB\u00EC\u00ED\u00EE\u00EF\u00F0\u00F2\u00F3\u00F4\u00F5\u00F6\u00F8\u00F9\u00FA\u00FB\u00FC\u00FD\u00FF\u0100\u0101\u0102\u0103\u0104\u0105\u0112\u0113\u0114\u0115\u0116\u0117\u0118\u0119\u011A\u011B\u0128\u0129\u012A\u012B\u012C\u012D\u012E\u012F\u0130\u0131\u014C\u014D\u014E\u014F\u0150\u0151\u0152\u0153\u0168\u0169\u016A\u016B\u016C\u016D\u016E\u016F\u0170\u0171\u0172\u0173\u0176\u0177\u0178]([^aeiouy\u00C0\u00C1\u00C2\u00C3\u00C4\u00C5\u00C6\u00C8\u00C9\u00CA\u00CB\u00CC\u00CD\u00CE\u00CF\u00D1\u00D2\u00D3\u00D4\u00D5\u00D6\u00D8\u00D9\u00DA\u00DB\u00DC\u00DD\u00E0\u00E1\u00E2\u00E3\u00E4\u00E5\u00E6\u00E8\u00E9\u00EA\u00EB\u00EC\u00ED\u00EE\u00EF\u00F0\u00F2\u00F3\u00F4\u00F5\u00F6\u00F8\u00F9\u00FA\u00FB\u00FC\u00FD\u00FF\u0100\u0101\u0102\u0103\u0104\u0105\u0112\u0113\u0114\u0115\u0116\u0117\u0118\u0119\u011A\u011B\u0128\u0129\u012A\u012B\u012C\u012D\u012E\u012F\u0130\u0131\u014C\u014D\u014E\u014F\u0150\u0151\u0152\u0153\u0168\u0169\u016A\u016B\u016C\u016D\u016E\u016F\u0170\u0171\u0172\u0173\u0176\u0177\u0178]*)$/;
d.abbreviate=function(b,a){var d=b.replace(u,"");if(d){if(b=function(){var b="",c=d.replace(n,"$1$3$5_$2$4$6").split(t);c.length>a&&(c=c.slice(0,a));var e=Math.floor(a/c.length),f=a-e*c.length;c.forEach(function(a){a.length<e&&(f+=e-a.length)});c.forEach(function(a,c){b+=c?a[0].toUpperCase():a[0].toLowerCase();a=a.slice(1);c=e-1;f&&a.length>c&&(f--,c++);for(;a.length>c;)a=q.test(a)?a.replace(q,"$1"):a.slice(0,c);a.length&&(b+=a.toLowerCase())});return{v:b}}(),"object"===("undefined"===typeof b?"undefined":
h(b)))return b.v}else return l("refMarkers.abbreviate failed, possibly due to non-latin character set. returning empty string."),""};d.abbreviateSlotName=function(b){if(!b)return"";var a=b.split("-"),c=g[a[0]];return c!==f?c+a[1]:d.abbreviate(b,3)};return d})});
/* ******** */
(function(d){var f=window.AmazonUIPageJS||window.P,g=f._namespace||f.attributeErrors,c=g?g("AudibleChexCoreAssets",""):f;c.guardFatal?c.guardFatal(d)(c,window):c.execute(function(){d(c,window)})})(function(d,f,g){d.when("AudiblejQuery","ready").register("ajaxInitiator",function(c){function d(a){if("undefined"===typeof a)throw new b("No Data provided for ajax call");if("undefined"===typeof a.operation)throw new b("No method or operation provided in caller data for Ajax call ");if("undefined"===typeof a.targetDiv)throw new b("No target Div provided in caller data for Ajax call ");
if("undefined"===typeof a.url)throw new b("No url provided in caller data for Ajax call "+a.operation);if("undefined"===typeof a.dataType)throw new b("No response format provided in caller data for Ajax call "+a.operation);if("undefined"===typeof a.data)throw new b("No parameters provided in caller data for Ajax call "+a.operation);}function b(a){this.message=a;this.name="AjaxIOException"}return{initiateAjaxCall:function(a,b){try{d(a)}catch(n){console.log(n.message);return}"undefined"!==typeof b&&
"undefined"!==typeof b.preAjaxCallOperations&&b.preAjaxCallOperations(a.targetDiv);c.ajax({url:a.url,type:"POST",async:null!==a.async?a.async:!0,dataType:a.dataType,data:a.data,success:function(c){if("undefined"!==typeof b&&"undefined"!==typeof b.onAjaxSuccess)b.onAjaxSuccess(a.targetDiv,c)},error:function(c){if("undefined"!==typeof b&&"undefined"!==typeof b.onAjaxFailure)b.onAjaxFailure(a.targetDiv,c)},complete:function(c){if("undefined"!==typeof b&&"undefined"!==typeof b.onAjaxComplete)b.onAjaxComplete(a.targetDiv,
c)}})}}});"use strict";d.when("AudiblejQuery","StrictEvents","ready").register("countdownTimer",function(c,d){var b={existingCountDowns:{}},a=new d(["audibleCountdownTimerStarted","audibleCountdownTimerEnded"]);b.on=a.on.bind(a);b.off=a.off.bind(a);b._emit=a.emit.bind(a);var f=function(e,b){var a,d,f,l=c("#"+b);if(l){var h=l.data("includeSeconds")||!1;b=l.data("trimZeros")||!1;d=Math.floor(e/864E5);var m=864E5*d;a=Math.floor((e-m)/36E5);var g=36E5*a;f=0;var k=(e-m-g)/6E4;h?(h=Math.floor(k),f=Math.ceil((e-
m-g-6E4*h)/1E3),60===f&&(h++,f=0)):h=Math.ceil(k);60===h&&(a++,h=0);24===a&&(d++,a=0);e=d;d=h;k=l.data("timeFormat")||"{d}d {h}h {m}m {s}s";m=l.data("timeFormatHms")||"{h}h {m}m {s}s";g=l.data("timeFormatMs")||"{m}m {s}s";h=l.data("timeFormatS")||"{s}s";b&&("0"===e.toString()&&"0"===a.toString()&&"0"===d.toString()?k=h:"0"===e.toString()&&"0"===a.toString()?k=g:"0"===e.toString()&&(k=m));k=k.replace("{d}",e.toString()).replace("{h}",a.toString()).replace("{m}",d.toString()).replace("{s}",f.toString());
l.text(k)}else throw"Timer ID not found: "+b;},n=function(e,c){e in b.existingCountDowns?console.warn("Duplicate Timer ID detected: "+e):function(){b.existingCountDowns[e]={totalCountDown:c,elapsedMillis:0,startingTime:(new Date).getTime()};f(c,e);var d=b.existingCountDowns[e];a.emit("audibleCountdownTimerStarted",e);var g=setInterval(function(){d.elapsedMillis=(new Date).getTime()-d.startingTime;var c=d.totalCountDown-d.elapsedMillis;0>c?(clearInterval(g),f(0,e),delete b.existingCountDowns[e],a.emit("audibleCountdownTimerEnded",
e)):f(c,e)},1E3)}()};b.start=function(){c(".adbl-countdown-timer").length&&c(".adbl-countdown-timer").each(function(){var a=c(this).attr("id");if(null!==a){var b=c(this).data("duration");if(b===g)throw"Timer "+a+" does not specify a duration";n(a,b)}else throw"One or more timers do not have an id";})};b.getRemainingTime=function(a){return a in b.existingCountDowns?(a=b.existingCountDowns[a],a=a.totalCountDown-a.elapsedMillis,0<a?a:0):-1};return b})});
/* ******** */
(function(c){var d=window.AmazonUIPageJS||window.P,b=d._namespace||d.attributeErrors,a=b?b("AudibleAYCLBuyBoxAssets",""):d;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,d,b){c.when("AudiblejQuery","setReviewProductRatings","button","ready").execute(function(a,c,d){a(document).on("click",".adbl-buy-box-add-to-library",function(b){b.preventDefault();d.disable(a(this)[0]);a(this).find(".bc-button-text-inner").html(a("#adbl_web_buybox_adding_to_library").data("value"));
var e=a(this).attr("id");b=a("#csrfToken-"+e).val();a.ajax({url:"/a/pd/addToLibrary",data:{asin:e,csrfToken:b},success:function(b){a("#adbl-member-buy-box-"+e).parent().parent().parent().replaceWith(b);c.setReviewProductRatings(".asinForRatingStars",".adbl-prod-rate-review-bar-group",".adbl-prod-rate-review-bar",".adbl-prod-rate-review-bar-overall",".adbl-prod-rate-review-bar-performance",".adbl-prod-rate-review-bar-story")}});"undefined"!==typeof digitalData.product&&digitalData.product?digitalData.product[0].productInfo.productID=
e:digitalData.product=[{productInfo:{productID:e}}];_satellite.track("addToLibrary")})})});
/* ******** */
(function(d){var a=window.AmazonUIPageJS||window.P,c=a._namespace||a.attributeErrors,b=c?c("AudibleBrickCitySharedAssets",""):a;b.guardFatal?b.guardFatal(d)(b,window):b.execute(function(){d(b,window)})})(function(d,a,c){d.when("AudiblejQuery","modal","ratingStarsInit","ready").execute(function(b,d,a){var c,e,f;b(".review-ineligible-trigger").on("click",function(a){c=b(a.currentTarget).attr("data-star-count");e=b(a.currentTarget).find(".bc-rating-stars");f=b(a.currentTarget).find(".bc-tooltip");digitalData.libraryAsin=
a.currentTarget.getAttribute("asin");_satellite.track("audible.review.ineligible")});b(".review-ineligible-modal.bc-modal-closeable").on("click",function(){e&&0<e.size()&&(a.setStarCount(c,e[0]),f.addClass("bc-hidden"))})})});
/* ******** */
(function(g){var l=window.AmazonUIPageJS||window.P,q=l._namespace||l.attributeErrors,a=q?q("AudibleBuyBoxAssets",""):l;a.guardFatal?a.guardFatal(g)(a,window):a.execute(function(){g(a,window)})})(function(g,l,q){g.when("AudiblejQuery","ajaxInitiator","refMarkers","ready").execute(function(a,c,b){function d(a){var c=a.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");c.find(".adblBuyBoxCartErrorAlert").addClass("bc-hidden");c.find(".adblBuyBoxAddToWishlistErrorAlert").addClass("bc-hidden");c.find(".adblBuyBoxRemoveFromWishlistErrorAlert").addClass("bc-hidden");
c.addClass("bc-hidden");a=a.find(".adblAddToCartButton");a.addClass("bc-button-disabled");a.find(".adblAddToCartText").addClass("bc-hidden");a.find(".adblAddingText").removeClass("bc-hidden");a.unbind("click")}function e(c,b){b=c.find(".adblGoToCartButton");c.find(".adblAddToCartButton").addClass("bc-hidden");b.removeClass("bc-hidden");if(h)h.incrementCartCount();else if((c=a("header .bc-icon-cart"))&&1===c.length){b=a("span.cart-num");var d;0===b.length?(d=0,b=a("\x3cspan\x3e"),b.addClass("cart-num"),
c.parent().parent().append(b)):d=parseInt(b.text(),10);b.html(d+1)}}function f(a,c){c=a.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");c.find(".adblBuyBoxCartErrorAlert").removeClass("bc-hidden");c.removeClass("bc-hidden");a=a.find(".adblAddToCartButton");a.click(k);a.find(".adblAddingText").addClass("bc-hidden");a.find(".adblAddToCartText").removeClass("bc-hidden");a.removeClass("bc-button-disabled")}function m(a,c){}function k(n){n=a(n.target).closest(".adblAddToCart");var h={},k={};h.url=
"/cart/add";h.operation="ADD_TO_CART";h.dataType="json";h.targetDiv=n;k.asin=n.find('input[name\x3d"asin"]').val();k.token=n.find('input[name\x3d"token"]').val();k.key=n.find('input[name\x3d"key"]').val();k.tr=n.find('input[name\x3d"tr"]').val();k.ct=n.find('input[name\x3d"ct"]').val();h.data=k;k={};k.preAjaxCallOperations=d;k.onAjaxSuccess=e;k.onAjaxFailure=f;k.onAjaxComplete=m;"undefined"!==typeof digitalData.product&&digitalData.product?digitalData.product[0].productInfo.productID=h.data.asin:
digitalData.product=[{productInfo:{productID:h.data.asin}}];"undefined"!==typeof _satellite&&_satellite&&_satellite.track("cartAdd");c.initiateAjaxCall(h,k);b.buildAndPost("cartAdd",n[0])}a(".adblAddToCartButton").click(k);a(".adblBuyForButton").click(function(){"undefined"!==typeof _satellite&&_satellite&&_satellite.track("cartAdd")});a(".adblBuyForLink").on("click",function(a){a.preventDefault();"undefined"!==typeof _satellite&&_satellite&&_satellite.track("cartAdd");this.closest("form").submit()});
var h;g.when("headerCart").execute(function(a){h=a})});"use strict";g.when("AudiblejQuery","wishlistUtil","ajaxInitiator","refMarkers","ready").execute(function(a,c,b,d){function e(a){c.hideAllErrorMessages(a);a=a.find(".adblAddToWishlistButton, .adblAddToWishlistLink");c.showInterStateText(a,".adblAddingToWishlistText",".adblAddToWishlistText")}function f(a,b){b=a.find(".adblGoToWishlistButton, .adblGoToWishlistLink, .adblRemoveFromWishlistButton, .adblRemoveFromWishlistLink");a=a.find(".adblAddToWishlistButton, .adblAddToWishlistLink");
c.changeClickableStateOnSuccess(a,b,".adblRemovingFromWishlistText",".adblRemoveFromWishlistText")}function m(a,b){c.displayErrorMessageOnFailure(a,".adblBuyBoxAddToWishlistErrorAlert");a=a.find(".adblAddToWishlistButton, .adblAddToWishlistLink");a.click(h);c.changeClickableStateOnFailure(a,".adblAddingToWishlistText",".adblAddToWishlistText")}function k(a,c){}function h(n){var h=a(n.target).closest(".wishlist"),h=c.buildWishlistCaller(h,"/wish-list/add","ADD_TO_WISHLIST"),g=c.buildWishlistCallback(e,
f,m,k);"undefined"!==typeof digitalData.product&&digitalData.product?digitalData.product[0].productInfo.productID=h.data.asin:digitalData.product=[{productInfo:{productID:h.data.asin}}];var l=a(n.target).closest("button").attr("contentType");digitalData.clickedAsinContentType=l;"undefined"!==typeof _satellite&&_satellite&&_satellite.track("wishlistAddClick");b.initiateAjaxCall(h,g);d.buildAndPost("wishlistAddClick",n.target)}a(".adblAddToWishlistButton, .adblAddToWishlistLink").click(h)});"use strict";
g.when("AudiblejQuery","wishlistUtil","ajaxInitiator","refMarkers","ready").execute(function(a,c,b,d){function e(a){c.hideAllErrorMessages(a);a=a.find(".adblRemoveFromWishlistButton, .adblRemoveFromWishlistLink");c.showInterStateText(a,".adblRemovingFromWishlistText",".adblRemoveFromWishlistText")}function f(a,b){b=a.find(".adblAddToWishlistButton, .adblAddToWishlistLink");a=a.find(".adblGoToWishlistButton, .adblGoToWishlistLink, .adblRemoveFromWishlistButton, .adblRemoveFromWishlistLink");c.changeClickableStateOnSuccess(a,
b,".adblAddingToWishlistText",".adblAddToWishlistText")}function m(a,b){c.displayErrorMessageOnFailure(a,".adblBuyBoxRemoveFromWishlistErrorAlert");a=a.find(".adblRemoveFromWishlistButton, .adblRemoveFromWishlistLink");a.click(h);c.changeClickableStateOnFailure(a,".adblRemovingFromWishlistText",".adblRemoveFromWishlistText")}function k(a,c){g.now("WishlistAssets").execute(function(a){null!==a&&a!==q&&a.handleRemoveFromWishlist()})}function h(h){var r=a(h.target).closest(".wishlist"),g=c.buildWishlistCaller(r,
"/wish-list/remove","REMOVE_FROM_WISHLIST"),l=c.buildWishlistCallback(e,f,m,k),r=r.find("[data-asin]");digitalData.clickedAsin=r.data("asin");digitalData.clickedAsinContentType=r.data("content-type");"undefined"!==typeof _satellite&&_satellite&&_satellite.track("wishlistRemoveClick");b.initiateAjaxCall(g,l);d.buildAndPost("wishlistRemoveClick",h.target)}a(".adblRemoveFromWishlistButton, .adblRemoveFromWishlistLink").click(h)});"use strict";g.when("AudiblejQuery","ready").register("wishlistUtil",function(a){return{buildWishlistCaller:function(a,
b,d){var e={},f={};e.url=b;e.operation=d;e.dataType="json";e.targetDiv=a;f.asin=a.find('input[name\x3d"asin"]').val();f.token=a.find('input[name\x3d"token"]').val();f.key=a.find('input[name\x3d"key"]').val();e.data=f;return e},buildWishlistCallback:function(a,b,d,e){var f={};f.preAjaxCallOperations=a;f.onAjaxSuccess=b;f.onAjaxFailure=d;f.onAjaxComplete=e;return f},hideAllErrorMessages:function(a){a=a.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");a.find(".adblBuyBoxCartErrorAlert").addClass("bc-hidden");
a.find(".adblBuyBoxAddToWishlistErrorAlert").addClass("bc-hidden");a.find(".adblBuyBoxRemoveFromWishlistErrorAlert").addClass("bc-hidden");a.addClass("bc-hidden")},showInterStateText:function(a,b,d){a.addClass("bc-button-disabled");a.find(d).addClass("bc-hidden");a.find(b).removeClass("bc-hidden")},changeClickableStateOnSuccess:function(a,b,d,e){a.addClass("bc-hidden");b.find(d).addClass("bc-hidden");b.find(e).removeClass("bc-hidden");b.removeClass("bc-button-disabled");b.removeClass("bc-hidden")},
displayErrorMessageOnFailure:function(a,b){a=a.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");a.find(b).removeClass("bc-hidden");a.removeClass("bc-hidden")},changeClickableStateOnFailure:function(a,b,d){a.find(b).addClass("bc-hidden");a.find(d).removeClass("bc-hidden");a.removeClass("bc-button-disabled")}}});"use strict";g.when("AudiblejQuery","refMarkers","focus","Spinner","button","modal","parentalControls","ready").execute(function(a,c,b,d,e,f,m){function k(a){switch(a){case "desktop":a=
"dt";break;case "mobile":a="mb";break;case "tablet":a="tb";break;default:a="tb"}return a}function h(a){return b.change({focusElement:a.find("button:eq(0)").get(0)||a.get(0)})}function n(c){var b=a(c.evt.target).closest(".adblBuyBoxArea"),d=b.find(".adblCalltoActionContainer").first(),b=b.find(c.id);b.addClass("buyBoxCurrentAction").slideDown(h(b));d.slideUp();"undefined"!==typeof _satellite&&_satellite&&_satellite.track(c.tracker)}function r(c){var b=a(c.evt.target).closest(".adblBuyBoxArea"),d=b.find(".adblCalltoActionContainer");
c=b.find(c.id);d.slideDown(h(d));c.removeClass("buyBoxCurrentAction").slideUp()}function l(a){"undefined"!==typeof digitalData.product&&digitalData.product?digitalData.product[0].productInfo.buyNowType=a:digitalData.product=[{productInfo:{buyNowType:a}}]}function t(u,d,h,n,w){if(u.find("button").is(":disabled"))return!1;var g=u.get(0),r=g.querySelector(".bc-button-text-inner"),t=r.textContent,y=g.querySelector(".bc-button-text").dataset;w=y.loading;var p=void 0;w?(e.disable(g),r.textContent=w):p=
q(n,u);l(d);c.post(h+k(a(".deviceType").val()));"undefined"!==typeof _satellite&&_satellite&&_satellite.track(d);var v=g.closest("form"),J=function(){e.enable(g);r.textContent=t;p&&p.stop()},E=function(){return m.canPurchaseProceed(function(a){a?v.submit():J()})};w&&y.showConfirmModal?function(){var c=document.getElementById("confirm-modal"),u=function(){f.open(c);b.change({focusElement:c.querySelector(b.FOCUSABLE_SELECTOR),isFocusOnLayer:!0})};y.modalInit?u():a.ajax({url:"/order-lookup/asin",method:"POST",
contentType:"application/json",data:JSON.stringify({asins:[v.elements.asin.value],token:v.elements.token.value,key:v.elements.key.value}),dataType:"json",success:function(a){a.url?(y.modalInit="true",document.getElementById("adbl-review-previous-order-button").querySelector(".bc-button-text").setAttribute("href",a.url),document.getElementById("adbl-place-new-order-button").addEventListener("click",E),c.querySelector(".modal-close").addEventListener("click",J),c.addEventListener("click",function(a){a.target.classList.contains("bc-modal-closeable")&&
J()}),u()):E()}}).fail(E)}():E();return!1}function q(a,c){var b=d.DISPLAY_TYPE_DEFAULT;c.closest(".pdp-hero-buy-box").length&&(b=d.DISPLAY_TYPE_TRANSPARENT);a=new d(c.closest(a).get(0),b);a.start();return a}var A=void 0;g.when("tray").execute(function(a){return A=a});var p=!1;a("#discovery_buyBox_moreOptions").click(function(){p=!0});a("#discovery_buyBox_moreOptions_tray").find(".bc-trigger").click(function(){p=!1});a("#discovery_buyBox_moreOptions_modal").find(".bc-trigger").click(function(){p=!1});
a(".adblConfirmCreditPurchase").css("display","none").removeClass("bc-hidden");a(".adblConfirmCashPurchase").css("display","none").removeClass("bc-hidden");a(".adblConfirmEnterprisePurchase").css("display","none").removeClass("bc-hidden");a(".adblDiscoveryConfirmCreditPurchase").css("display","none").removeClass("bc-hidden");a(".adblDiscoveryConfirmCashPurchase").css("display","none").removeClass("bc-hidden");a(".adblBuyNowWithCredit").click(function(b){b={evt:b,id:".adblConfirmCreditPurchase",tracker:"buyNowCreditCartAddClick"};
c.post("1clk_bb_shw_bn_1crdt_"+k(a(".deviceType").val()));n(b)});a(".adblConfirmCreditCancelButton").click(function(b){r({evt:b,id:".adblConfirmCreditPurchase"});c.post("1clk_bb_cncl_crdt_cnfrm_"+k(a(".deviceType").val()))});a(".adblBuyNowCashButton").click(function(b){b={evt:b,id:".adblConfirmCashPurchase",tracker:"buyNowCashCartAddClick"};c.post("1clk_bb_shw_bn_cash_"+k(a(".deviceType").val()));a("channelLiteProduct").length&&c.post("1clk_bb_shw_audshw_add2lib4cash_"+k(a(".deviceType").val()));
var d=a(b.evt.target).closest(".adblBuyBoxArea"),h=d.find(".adblCalltoActionContainer").first();0===d.parent().find(".adblBuyBoxArea \x3e .adblConfirmCashPurchase").length&&h.after(d.find(b.id));n(b)});a(".adblConfirmCashCancelButton").click(function(b){r({evt:b,id:".adblConfirmCashPurchase"});c.post("1clk_bb_cncl_csh_cnfrm_"+k(a(".deviceType").val()));a("channelLiteProduct").length&&c.post("1clk_bb_cncl_audshw_cnfrm_"+k(a(".deviceType").val()))});a(".enterprisePurchaseButton").click(function(b){b=
{evt:b,id:".adblConfirmEnterprisePurchase",tracker:"enterpriseAddToLibraryClick"};c.post("1clk_bb_shw_ntprs_purchs_"+k(a(".deviceType").val()));n(b)});a(".adblConfirmEnterpriseCancelButton").click(function(b){r({evt:b,id:".adblConfirmEnterprisePurchase"});c.post("1clk_bb_cncl_ntprs_cnfrm_"+k(a(".deviceType").val()))});a(".adblDiscoveryBuyNowWithCreditButton").click(function(b){b={evt:b,id:".adblDiscoveryConfirmCreditPurchase",tracker:"buyNowCreditCartAddClick"};var d=a(b.evt.target).parent().attr("credit");
digitalData.creditPrice=d;c.post("1clk_bb_shw_bn_1crdt_"+k(a(".deviceType").val()));var d=a(b.evt.target).closest(".adblBuyBoxArea"),h=d.find(".adblCalltoActionContainer").first();0===d.parent().find(".adblBuyBoxArea \x3e .adblDiscoveryConfirmCreditPurchase").length&&h.after(d.find(b.id));n(b)});a(".adblDiscoveryConfirmCreditCancelButton").click(function(b){r({evt:b,id:".adblDiscoveryConfirmCreditPurchase"});c.post("1clk_bb_cncl_crdt_cnfrm_"+k(a(".deviceType").val()))});a(".adblConfirmCreditPurchaseButton").click(function(b){return t(a(this),
"buyNowCreditPurchase","1clk_bb_cnfrm_crdt_purchs_","#adbl-confirm-credit-purchase",b)});a(".adblConfirmCashPurchaseButton").click(function(b){b=t(a(this),"buyNowCashPurchase","1clk_bb_cnfrm_csh_purchs_","#adbl-confirm-cash-purchase",b);a("channelLiteProduct").length&&c.post("1clk_bb_cnfm_audshw_purchs_"+k(a(".deviceType").val()));return b});a(".adblDiscoveryConfirmCreditPurchaseButton").click(function(b){return t(a(this),"buyNowCreditPurchase","1clk_bb_cnfrm_crdt_purchs_","#adbl-confirm-credit-purchase",
b)});var v=document.getElementById("discovery_buyBox_moreOptions_modal");v&&a("#paymentsWidgetDialog").find(".bc-trigger").find(".bc-icon-close").click(function(a){p&&(a.preventDefault(),a.stopPropagation(),f.toggle(v))});var w=document.getElementById("discovery_buyBox_moreOptions_tray");w&&a("#paymentsWidgetDialog").find(".payments-widget-close-dialog").click(function(a){p&&(a.preventDefault(),a.stopPropagation(),A.toggle(w))})});"use strict";"use strict";g.when("AudiblejQuery","countdownTimer",
"ready").register("specialPromoBuyBoxCallBacks",function(a,c){a("#showSpecialPromoTray").length||c.start();return{addToSpecialPromoTrayCallBack:function(b){var c=b.next(".spActionData").data("asin");b.addClass("bc-pub-hidden");a(".sp-in-selection-"+c).removeClass("bc-pub-hidden");a(".sp-add-to-selection-"+c).addClass("bc-pub-hidden")},removeFromSpecialPromoTrayCallBack:function(b){b=b.next(".spActionData").data("asin");a('.addToSpecialPromoTrayBtn button[data-asin\x3d"'+b+'"]').parent(".addToSpecialPromoTrayBtn").removeClass("bc-pub-hidden");
a(".sp-in-selection-"+b).addClass("bc-pub-hidden");a(".sp-add-to-selection-"+b).removeClass("bc-pub-hidden")}}});"use strict";g.when("AudiblejQuery","cloudPlayerLauncher","ready").execute(function(a,c){a(document).on("click",".adblBuyBoxListenNow",function(b){b.preventDefault();b=a(this).children(".bc-button-text").attr("asin");null!==b&&b!==q&&c.openCloudPlayer(b,"a_ownedbuybox_cloudplayer")})});"use strict";g.when("AudiblejQuery","geoRights","paymentsWidget","issuerIconUtility").execute(function(a,
c,b,d){function e(b){if("undefined"===typeof b||null===b)a("#adbl-payment-instrument-details").addClass("bc-hidden"),a("#adbl-payment-invalid-instr-error").addClass("bc-hidden"),a("#adbl-payment-geoblocked-instr-error").addClass("bc-hidden"),a("#adbl-payment-noInstr-error").removeClass("bc-hidden"),a(".adblConfirmCashPurchaseButton").hasClass("bc-button-disabled")||(a("#adbl-confirm-cash-purchase-form").find('input[name\x3d"paymentId"]').val(""),k());else{var e=a("#adbl-confirm-cash-purchase-form");
e.find('input[name\x3d"paymentId"]').val();var g=b.paymentId;b.isValid?c.validateGeoRights(e,b.billingAddressId).then(function(c){if(c){c=b.paymentId;var e=a("#adbl-payment-instrument-details").find(".buy-box-issuer-icon");d.updateImage(e.get(0),b);a("#adbl-payment-instrument-details").find(".adblCCTail").html(b.tail);a("#adbl-confirm-cash-purchase-form").find('input[name\x3d"paymentId"]').val(c);a("#adbl-payment-instrument-details").removeClass("bc-hidden");a("#adbl-payment-invalid-instr-error").addClass("bc-hidden");
a("#adbl-payment-noInstr-error").addClass("bc-hidden");a("#adbl-payment-geoblocked-instr-error").addClass("bc-hidden");a(".adblConfirmCashPurchaseButton").hasClass("bc-button-disabled")&&m()}else f(b)},function(){f(b)}):(a("#adbl-payment-instrument-details").addClass("bc-hidden"),a("#adbl-payment-noInstr-error").addClass("bc-hidden"),a("#adbl-payment-geoblocked-instr-error").addClass("bc-hidden"),a("#adbl-payment-invalid-instr-error").removeClass("bc-hidden"),a(".adblConfirmCashPurchaseButton").hasClass("bc-button-disabled")||
k(),a("#adbl-confirm-cash-purchase-form").find('input[name\x3d"paymentId"]').val(g))}}function f(b){b=b.paymentId;a("#adbl-payment-instrument-details").addClass("bc-hidden");a("#adbl-payment-noInstr-error").addClass("bc-hidden");a("#adbl-payment-invalid-instr-error").addClass("bc-hidden");a("#adbl-payment-geoblocked-instr-error").removeClass("bc-hidden");a(".adblConfirmCashPurchaseButton").hasClass("bc-button-disabled")||(a("#adbl-confirm-cash-purchase-form").find('input[name\x3d"paymentId"]').val(b),
k())}function m(){a(".adblConfirmCashPurchaseButton").removeClass("bc-button-disabled");a(".adblConfirmCashPurchaseButton").find("button").prop("disabled",!1)}function k(){a(".adblConfirmCashPurchaseButton").addClass("bc-button-disabled");a(".adblConfirmCashPurchaseButton").find("button").prop("disabled",!0)}a(".changePaymentInstr").click(function(a){a.preventDefault();b.openPaymentsWidgetView(b.PAYMENTS_LIST_VIEW_NAME)});a(".addnewAddress").click(function(a){a.preventDefault();b.openPaymentsWidgetView(b.ADD_ADDRESS_VIEW_NAME)});
b.on("addAddress",function(b,d){if("undefined"!==typeof d&&null!==d&&!1!==d.success){var f=d.addressId;if("undefined"===typeof f||null===f)return null;var e=a(".buyBoxCurrentAction #adbl-address-error");c.validateGeoRights(e,f).then(function(b){b?(e.addClass("bc-hidden"),a(".adblConfirmCashPurchaseButton").hasClass("bc-button-disabled")&&m(),a(".adblConfirmCreditPurchaseButton").hasClass("bc-button-disabled")&&(a(".adblConfirmCreditPurchaseButton").removeClass("bc-button-disabled"),a(".adblConfirmCreditPurchaseButton").find("button").prop("disabled",
!1)),a("#adbl-confirm-credit-purchase-form").find('input[name\x3d"addressId"]').val(f),a("#adbl-confirm-cash-purchase-form").find('input[name\x3d"addressId"]').val(f)):l.location.reload()},function(){l.location.reload()})}});b.on("confirmSelectedPayment",function(a,b){"undefined"!==typeof b&&null!==b&&e(b.paymentInstrument)});b.on("addPayment",function(a,c){"undefined"!==typeof c&&null!==c&&c.success&&b.isPaymentsWidgetDialogOpen()&&e(c.paymentInstrument)})});"use strict";g.when("AudiblejQuery","ajaxInitiator",
"ready").register("geoRights",function(a,c){function b(b){return new Promise(function(c,f){a.ajax({url:b.url,type:"POST",async:!0,dataType:b.dataType,data:b.data}).done(function(a){c(a.success)}).fail(function(a){f(!1)})})}return{validateGeoRights:function(a,c){var f={},m={};f.url="/a/buy-box/validate";f.operation="VALIDATE_GEO_RIGHTS";f.dataType="json";f.targetDiv=a;a=a.parent().find("form");m.asin=a.find('input[name\x3d"asin"]').val();m.asin&&0!==m.asin.length||(m.asin=a.find('input[name\x3d"giftAsin"]').val());
m.token=a.find('input[name\x3d"token"]').val();m.key=a.find('input[name\x3d"key"]').val();m.billingAddressId=c;f.data=m;return b(f)}}});"use strict";g.when("AudiblejQuery","setReviewProductRatings","ready").execute(function(a,c){c.setReviewProductRatings(".asin-for-rating-stars",".ratings-csrf-token",".adbl-prod-rate-review-bar-group",".adbl-prod-rate-review-bar",".adbl-prod-rate-review-bar-overall",".adbl-prod-rate-review-bar-performance",".adbl-prod-rate-review-bar-story")});"use strict";g.when("AudiblejQuery",
"button","refMarkers","Spinner","minervaBridgeUtil","ready").execute(function(a,c,b,d,e){function f(a){a=new d(a.get(0),d.DISPLAY_TYPE_DEFAULT);a.start();return a}function m(a){a&&(a.stop(),a.remove())}function k(){a(".return-book-button").each(function(){c.disable(this)})}function h(){a(".romance-add-to-library-button").each(function(){c.disable(this)})}function n(b){var d=a(".romance-add-to-library-button");m(b);d.each(function(){c.enable(this)})}function r(b,c){a.ajax({url:"/aycl-return-flow?asin\x3d"+
b,type:"GET",success:function(b){0===a("#return-flow-view").length&&(a("body").append(b),I&&I(document.getElementById("return-flow-view")));a(".return-book-button").off("click").on("click",D(c));a("#cancel-return-flow-button").off("click").on("click",t(c));u();L();a("#return-form, input[type\x3dradio]").attr("checked",!1)},error:function(){F();n(c)}})}function L(){a("#return-form, input:checked").change(function(){a(".return-book-button").each(function(){c.enable(this)})})}function t(d){return function(f){a(".return-book-button").each(function(){c.disable(this)});
if(e)e.onReturnFlowPresented(x.CANCELLED,"","",-1);u();n(d);b.buildAndPost("returnflowCancelClick",f.target)}}function D(c){return function(d){if(!a(".return-book-button").hasClass("bc-button-disabled")){G(a("#return-flow-view-alert"));k();var f=a("input[name\x3daudiobook]:checked").val();if(null!==f){b.buildAndPost("returnflowReturnBookClick",d.target);d=a("#order-num-"+f).val();var e=a("#hmac-"+f).val();A(f,d,e,c)}}}}function A(b,c,d,f){c={orderNum:c,hmac:d};var h=(new Date).getTime();a.ajax({url:w(b,
c),type:"DELETE",dataType:"json",success:function(){p(b,h,f)},error:function(){var c=(new Date).getTime()-h;if(e)e.onReturnFlowPresented(x.FAILED,b,"",c);a("#return-flow-view-alert").removeClass("bc-hidden");n(f)}})}function p(b,c,d){var f=a("#book-to-add").val(),h=a("#book-to-add-hmac").val();v(f,h,"adbl_rom_ar_rf_atl",function(){var a=(new Date).getTime()-c;if(e)e.onReturnFlowPresented(x.SUCCESS,b,f,a);u();B()},function(h){h=h.responseJSON;if(h!==q&&!0===h.limit_reached)a("input[value\x3d"+b+"]").closest("li").remove();
else{h=(new Date).getTime()-c;if(e)e.onReturnFlowPresented(x.FAILED,b,f,h);F();n(d)}})}function v(b,c,d,f,h){a.ajax({url:w(b,{hmac:c,ref:d}),type:"POST",dataType:"json",success:f,error:h})}function w(b,c){if(null===c||c===q)c={};c=a.param(c);return["/library/audiobook/"+b,c].join("?")}function u(){H.toggle(document.getElementById("return-flow-view"))}function F(){z.find(".adblBuyBoxRomanceAYCLErrorAlert").removeClass("bc-hidden");z.removeClass("bc-hidden")}function G(a){a.addClass("bc-hidden")}function K(){var a=
C("getAppModalWidgetType"),b=l.location,c=l.location.href.replace(l.location.search,""),d="?";a.getAppModalWidgetType="ROMANCE";for(var f in a)a.hasOwnProperty(f)&&(d+=f+"\x3d"+a[f]+"\x26");b.href=c+d}function B(){y?setTimeout(function(){K()},y):K()}function C(a){var b={};l.location.search.slice(1).split("\x26").map(function(a){return a.split("\x3d")}).reduce(function(b,c){var d=c[0];c=c[1];d&&0!==d.length&&d!==a&&(b[decodeURIComponent(d)]=decodeURIComponent(c));return b},b);return b}var x={SUCCESS:"SUCCESS",
FAILED:"FAILURE",CANCELLED:"CANCEL"},z=null,y=void 0,H=null,I=null;g.when("tray","mobile").execute(function(a){H=a;I=a.init});g.when("modal","desktop").execute(function(a){H=a});a(".romance-add-to-library-button").on("click",function(c){h();var d=c.target,k=a(d).closest("div[name\x3d'romance-add-to-library-form']"),m=k.find("input[name\x3d'asin']").val(),w=k.find("input[name\x3d'token']").val(),g=k.find("input[name\x3d'ref']").val(),u=(new Date).getTime();y=parseInt(k.find("input[name\x3d'delay']").val(),
10)||0;z=a(d).closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");var l=f(k);G(z.find(".adblBuyBoxRomanceAYCLErrorAlert"));G(z);v(m,w,g,function(){var a=(new Date).getTime()-u;if(e)e.onAddToLibrary(x.SUCCESS,m,a);B()},function(a){a=a.responseJSON;if(a!==q&&!0===a.limit_reached)r(a.asin,l),b.buildAndPost("returnflowLaunched",c.target);else{F();a=(new Date).getTime()-u;if(e)e.onAddToLibrary(x.FAILED,m,a);n(l)}})});k()});"use strict";g.when("AudiblejQuery","countdownTimer").execute(function(a,c){function b(a){a.closest(".adblBuyBoxContainer").find(".adblBuyNowCashButton, .adblBuyNowWithCredit").off("click").on("click",
function(){var a=d();a.cic="se";a.ref="a_bb_cic_se";var b=l.location.href.replace(l.location.search,""),c="?",h;for(h in a)a.hasOwnProperty(h)&&(c+=h+"\x3d"+a[h]+"\x26");l.location.href=b+c})}function d(){var a={};l.location.search.slice(1).split("\x26").map(function(a){return a.split("\x3d")}).reduce(function(a,b){var c=b[0];b=b[1];c&&0!==c.length&&(a[decodeURIComponent(c)]=decodeURIComponent(b));return a},a);return a}c.start();c.on("audibleCountdownTimerEnded",function(c,d){c=a("#"+d);c.hide();
d=c.closest(".adblSaleTimerContainer");d.find(".adblSaleHasEnded").show();d.find(".adblSaleEndsIn").hide();b(c)})});"use strict";g.when("AudiblejQuery","cloudPlayerLauncher","minervaBridgeUtil","refMarkerCommonUtil","ready").execute(function(a,c,b,d){function e(a,b){var c=b.getAttribute("asin"),d=b.getAttribute("contentType");b=b.getAttribute("asinListIndex");"undefined"!==typeof digitalData&&digitalData&&(digitalData.clickedAsin=c,digitalData.clickedAsinContentType=d,b&&(digitalData.clickedAsinListIndex=
parseInt(b,10)+1),"undefined"!==typeof _satellite&&_satellite&&_satellite.track(a))}a(document).on("click",".adblBuyBoxMinervaPlayNow",function(f){f.preventDefault();d.sendRefMarker("_1clk_bb_pl_",a(".deviceType").val());e("oneClickPlay",a(this)[0].querySelector('button[name\x3d"playButton"]'));if(null===b){var m=a(this).children(".bc-button-text");f=m.attr("asin");m=m.attr("contentDeliveryType");null!==f&&f!==q&&c.openCloudPlayer(f,"a_minerva_cloudplayer_[ASIN]".replace("[ASIN]",f),{contentDeliveryType:m})}});
a(document).on("click",".adblBuyBoxMinervaPlayNowConsumable",function(d){d.preventDefault();if(null===b){var e=a(this);d=e.attr("asin");e=e.attr("contentDeliveryType");null!==d&&d!==q&&c.openCloudPlayer(d,"a_minerva_cloudplayer_[ASIN]".replace("[ASIN]",d),{contentDeliveryType:e})}});a(document).on("click",".adblBuyBoxMinervaPause",function(b){b.preventDefault();d.sendRefMarker("_1clk_bb_ps_",a(".deviceType").val());e("oneClickPause",a(this)[0].querySelector('button[name\x3d"pauseButton"]'))})});"use strict";
g.when("AudiblejQuery","minervaBridgeUtil","modal","ready").execute(function(a,c,b){function d(a,d,h){if(c.on1ClickPlayButtonAction){if(h=d.getAttribute("asin"),d=d.getAttribute("contentDeliveryType"),h)c.on1ClickPlayButtonAction(a,h,d,!1,null)}else b.toggle(h)}function e(){return function(a,b,c){c=document.getElementsByClassName("adblBuyBoxMinervaPlayNow");for(var d=0;d<c.length;d++){var e=c[d].parentElement,g=c[d],l=e.querySelector(".adblBuyBoxMinervaPause"),e=e.querySelector('button[name\x3d"playButton"]').getAttribute("asin");
e!==q&&e===a&&b===f.PLAYING?(g.classList.contains("bc-hidden")||g.classList.add("bc-hidden"),l.classList.contains("bc-hidden")&&l.classList.remove("bc-hidden")):(g.classList.contains("bc-hidden")&&g.classList.remove("bc-hidden"),l.classList.contains("bc-hidden")||l.classList.add("bc-hidden"))}}}if(c){var f={PLAYING:"PLAYING",PAUSED:"PAUSED"};c.on1ClickPlayButtonAction&&(c.onNativePlayerChangeState=e(),c.on1ClickPlayButtonAction("REGISTER",null,null,!1,null));a(document).on("click",".adblBuyBoxMinervaPlayNow",
function(b){b.preventDefault();b=a(this)[0].querySelector('button[name\x3d"playButton"]');var c=a(this).parent().find(".adblBuyBoxMinervaPlayNowNoJSBridgeModal")[0];d("PLAY",b,c)});a(document).on("click",".adblBuyBoxMinervaPause",function(b){b.preventDefault();b=a(this)[0].querySelector('button[name\x3d"pauseButton"]');var c=a(this).parent().find(".adblBuyBoxMinervaPlayNowNoJSBridgeModal")[0];d("PAUSE",b,c)});a(document).on("click",".adblBuyBoxMinervaPlayNowConsumable",function(b){b.preventDefault();
b=a(this)[0];var c=a(this).parent().find(".adblBuyBoxMinervaPlayNowNoJSBridgeModal")[0];d("PLAY",b,c)})}});"use strict";g.when("AudiblejQuery","modal","refMarkerCommonUtil","ready").execute(function(a,c,b){a(document).on("click",".adbl-buybox-review-ineligibility-alert",function(c){c.preventDefault();c=a(this)[0].querySelector('button[name\x3d"adblBuyBoxReviewAlertButton"]').getAttribute("asin");b.sendRefMarker("_1clk_bb_inlegrnr_",a(".deviceType").val());"undefined"!==typeof digitalData&&digitalData&&
(digitalData.clickedAsin=c,"undefined"!==typeof _satellite&&_satellite&&_satellite.track("adblBuyBoxReviewIneligibleAlert"))})});"use strict";g.when("AudiblejQuery","refMarkers","ready").execute(function(a,c){g.register("refMarkerCommonUtil",function(){var a={getAbbreviatedDeviceType:function(a){switch(a){case "desktop":a="dt";break;case "mobile":a="mb";break;case "tablet":a="tb";break;default:a="dt"}return a},sendRefMarker:function(d,e){"undefined"!==typeof digitalData&&digitalData&&digitalData.page&&
digitalData.page.category&&digitalData.page.category.pageType?c.post(c.abbreviate(digitalData.page.category.pageType,3)+d+a.getAbbreviatedDeviceType(e)):c.post("unk"+d+a.getAbbreviatedDeviceType(e))}};return a})});"use strict";g.when("AudiblejQuery","ready").register("minervaBridgeUtil",function(a){a=["MobileJavaScriptBridge","AndroidJavaScriptBridge","StoreHandler"];a:{for(var c=0;c<a.length;++c){var b=a[c];if("undefined"!==typeof l[b]&&l[b]){a=l[b];break a}}a=null}return a});"use strict";g.when("AudiblejQuery",
"minervaBridgeUtil","refMarkerCommonUtil","Spinner","button","ready").execute(function(a,c,b,d,e){function f(a){a.hasClass("bc-hidden")&&a.removeClass("bc-hidden")}function g(a){a=new d(a.get(0),d.DISPLAY_TYPE_DEFAULT);a.start();return a}function k(a){a&&a instanceof d&&(a.stop(),a.remove())}function h(a,b){b=b.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");f(b.find(a));f(b)}function n(a,b){b=b.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");a=b.find(a);a.hasClass("bc-hidden")||a.addClass("bc-hidden");
b.hasClass("bc-hidden")||b.addClass("bc-hidden")}function l(b){a(b).each(function(a,b){e.disable(b)})}function q(b){a(b).each(function(a,b){e.enable(b)})}function t(b){var d=a(b.target).closest(b.data.form),f=d.find(b.data.buttonCssClass);if(e.isButtonDisabled(f.get(0)))return!1;var t=b.data.errorAlertCssClass,p=d.find("input[name\x3d'asin']").val(),B=parseInt(d.find("input[name\x3d'delay']").val(),10)||0,C=(new Date).getTime(),x=a(b.data.buttonCssClass).filter(function(a,b){return!e.isButtonDisabled(b)});
l(x);n(t,d);var z=g(d);"undefined"!==typeof digitalData.product&&digitalData.product?digitalData.product[0].productInfo.productID=p:digitalData.product=[{productInfo:{productID:p}}];"undefined"!==typeof _satellite&&_satellite&&_satellite.track("addToLibrary");D(d,"POST",function(){A(B);if(c)c.onAddToLibrary(v.SUCCESS,p,(new Date).getTime()-C)},function(a){h(t,d);k(z);q(x);if(c)c.onAddToLibrary(v.FAILURE,p,(new Date).getTime()-C)})}function D(b,c,d,e){var f=b.find("input[name\x3d'asin']").val(),h=
b.find("input[name\x3d'token']").val();b=b.find("input[name\x3d'ref']").val();a.ajax({url:p(f,{hmac:h,ref:b}),type:c,dataType:"json",success:d,error:e})}function A(a){setTimeout(function(){location.reload(!0)},a)}function p(b,c){c=a.param(c||{});return["/library/audiobook/"+b,c].join("?")}var v={SUCCESS:"SUCCESS",FAILED:"FAILURE"};a(".discovery-add-to-library-button").click({form:"div[name\x3d'discovery-add-to-library-form']",buttonCssClass:".discovery-add-to-library-button",errorAlertCssClass:".adblBuyBoxAddToLibraryErrorAlert"},
t);a(".adblFollowPodcastButton").click({form:".adblFollowPodcast",buttonCssClass:".adblFollowPodcastButton",errorAlertCssClass:".adblBuyBoxFollowPodcastErrorAlert"},t);a(".adblUnfollowPodcastButton").click({form:".adblFollowPodcast",buttonCssClass:".adblUnfollowPodcastButton",errorAlertCssClass:".adblBuyBoxUnfollowPodcastErrorAlert"},function(c){var d=a(c.target).closest(c.data.form),e=d.find(c.data.buttonCssClass),f=c.data.errorAlertCssClass,p=parseInt(d.find("input[name\x3d'delay']").val(),10)||
0;l(e);n(f,d);var t=g(d);b.sendRefMarker("_1clk_bb_rvfmlib_",a(".deviceType").val());"undefined"!==typeof digitalData&&digitalData&&(digitalData.clickedAsin=d.find("input[name\x3d'asin']").val(),"undefined"!==typeof _satellite&&_satellite&&_satellite.track("removeFromLibrary"));D(d,"DELETE",function(){A(p)},function(a){h(f,d);k(t);q(e)})})});"use strict";g.when("ready").register("parentalControls",function(){return{canPurchaseProceed:function(a){if(l.StoreHandler&&l.StoreHandler.onBuyAudiobookPressed){if(l.proceedCheckout)return a(!1);
l.proceedCheckout=function(c){l.proceedCheckout=q;a(c)};l.StoreHandler.onBuyAudiobookPressed()}else return a(!0)}}});"use strict";g.when("AudiblejQuery","minervaBridgeUtil","refMarkerCommonUtil","modal","ready").execute(function(a,c,b,d){function e(){return function(a,b){var c=document.querySelector(".adblBuyBoxMinervaSaveToLibrary"),d=document.querySelector(".adblBuyBoxMinervaViewInLibrary"),e=c.querySelector('button[name\x3d"saveToLibraryButton"]').getAttribute("asin");e!==q&&e===a&&b===g.SAVED_ON_LOCAL_DEVICE?
f(c,d):(c.classList.contains("bc-hidden")&&c.classList.remove("bc-hidden"),d.classList.contains("bc-hidden")||d.classList.add("bc-hidden"))}}function f(a,b){a.classList.contains("bc-hidden")||a.classList.add("bc-hidden");b.classList.contains("bc-hidden")&&b.classList.remove("bc-hidden")}if(c){var g={SAVED_ON_LOCAL_DEVICE:"SAVED_ON_LOCAL_DEVICE",NOT_ON_LOCAL_DEVICE:"NOT_ON_LOCAL_DEVICE"};if(c.getDownloadStatus&&c.downloadAsin){c.notifyDownloadStatus=e();var k=document.querySelector('button[name\x3d"saveToLibraryButton"]');
k&&(k=k.getAttribute("asin"))&&c.getDownloadStatus(k)}a(document).on("click",".adblBuyBoxMinervaSaveToLibrary",function(e){e.preventDefault();var g=a(this)[0].querySelector('button[name\x3d"saveToLibraryButton"]');e=g.getAttribute("asin");var k=g.getAttribute("contentType"),g=g.getAttribute("asinListIndex");b.sendRefMarker("_1clk_bb_svtlib_",a(".deviceType").val());"undefined"!==typeof digitalData&&digitalData&&(digitalData.clickedAsin=e,digitalData.clickedAsinContentType=k,g&&(digitalData.clickedAsinListIndex=
parseInt(g,10)+1),"undefined"!==typeof _satellite&&_satellite&&_satellite.track("adblBuyBoxDwonlaodContent"));if(c.downloadAsin){if(e=document.querySelector(".adblBuyBoxMinervaViewInLibrary"),k=this.querySelector('button[name\x3d"saveToLibraryButton"]').getAttribute("asin"))c.downloadAsin(k),f(this,e)}else d.toggle(a(this).parent().find(".adblBuyBoxMinervaSaveToLibraryNoJSBridgeModal")[0])})}});"use strict";g.when("AudiblejQuery","refMarkers","minervaBridgeUtil","ready").execute(function(a,c,b){a(".discovery-upsell-button").click(function(d){var e=
a(d.target).parent(),f=e.data("asin"),g=e.data("native-login-enabled"),e=e.attr("href");digitalData.clickedAsin=f;"undefined"!==typeof _satellite&&_satellite&&_satellite.track("membershipSignUp");c.buildAndPost("membershipSignUp",f);!0===g&&b&&b.launchAudiblePageAfterSignIn&&(d.preventDefault(),b.launchAudiblePageAfterSignIn(l.location.origin+e))})});"use strict";g.when("AudiblejQuery","minervaBridgeUtil","ready").execute(function(a,c){a(".rate-and-review-button").click(function(b){var d=a(b.target).parent(),
e=d.data("native-login-enabled"),d=d.data("relative-href");!0===e&&c&&c.launchAudiblePageAfterSignIn&&(b.preventDefault(),c.launchAudiblePageAfterSignIn(l.location.origin+d))})});"use strict";g.when("AudiblejQuery","ready").execute(function(a){a(".adbl_buybox_upsell_learn_more_link").click(function(){"undefined"!==typeof _satellite&&_satellite&&_satellite.track("learnMoreAboutMembershipClick")})});"use strict";g.when("AudiblejQuery","minervaBridgeUtil","ready").execute(function(a,c){a(".discovery-sign-in-to-listen-button").click(function(b){a(b.target);
var d=l.location.href;c&&c.launchAudiblePageAfterSignIn&&(b.preventDefault(),c.launchAudiblePageAfterSignIn(d))})});"use strict";g.when("AudiblejQuery","refMarkerCommonUtil","ready").execute(function(a,c){a(document).on("click",".adblPodcastEpisodesListButton",function(b){b=a(this).find("[data-asin]");digitalData.clickedAsin=b.data("asin");digitalData.clickedAsinContentType=b.data("content-type");a(".deviceType").val()&&c.sendRefMarker("_bb_view_all_ep_",a(".deviceType").val());"undefined"!==typeof _satellite&&
_satellite&&_satellite.track("adblBuyBoxViewAllEpisodes")})})});
/* ******** */
