(function(g){var c=window.AmazonUIPageJS||window.P,f=c._namespace||c.attributeErrors,h=f?f("AryaAnalyticsAssets",""):c;h.guardFatal?h.guardFatal(g)(h,window):h.execute(function(){g(h,window)})})(function(g,c,f){g.when("debounce","adobeUtils").execute(function(k,d){var f=k(function(){return d.scanForImpressions(document.body)},500,2E3);["scroll","resize","click"].forEach(function(d){return c.addEventListener(d,f)});f()});g.when("debounce","boxUtility","ready").register("adobeUtils",function(k,d){function l(a){d.isInView(a,
!0,!0)&&(a.classList.remove("adbl-asin-impression"),setTimeout(function(){d.isInView(a,!0,!0)?e(a):a.classList.add("adbl-asin-impression")},2E3))}function e(a){a.classList.remove("adbl-asin-impression");a.classList.add("adbl-impression-emitted");n.push(p(a));b()}function p(a){var b=a&&a.dataset;if(!b)return{};var d=a.closest(".slot"),c=a.closest(".adbl-impression-container"),c=b.widget||c&&c.dataset.widget||d&&d.children[0].id,d=d&&d.id,m=b.url;if(!m){var e=a.closest("a");if(e&&e.href)m=e.href;else if(e=
a.querySelector('a:not([href\x3d""])'))m=e.href}var e=b.faceOut||"0",v=a.closest(".product-carousel-item");v&&(e=v.dataset.slickIndex);return{widget:c,slotId:d,url:m,faceOut:e,asin:b.asin,position:b.position===f?String(Array.prototype.indexOf.call(a.parentElement.children,a)+1):b.position,ref:m&&g(m)||r,source:b.source||"EMPTY"}}function g(a){return(a=h.exec(a))?a[1]:null}var h=/[?&\/]ref=([^&#]*)/,r=g(c.location.href);if(!c.digitalData||!c.digitalData.page||!c.digitalData.page.category)throw Error("Error initializing adobeUtils.js: missing or invalid window.digitalData object \ud83d\ude2b");
var t="DETAIL"===c.digitalData.page.category.pageType?"DETAIL":c.digitalData.page.pageInfo.pageName,u=c.digitalData.webSessionId||"",n=[],q=k(function(a){var b=1<arguments.length&&arguments[1]!==f?arguments[1]:!1;if(!(a&&a instanceof HTMLElement))throw Error("scanForAsinImpressions: called without valid element \ud83d\ude1f");b=b?e:l;a.classList.contains("adbl-asin-impression")&&b(a);Array.prototype.slice.call(a.getElementsByClassName("adbl-asin-impression")).forEach(b)}),b=k(function(){var a=c._satellite&&
c._satellite.getToolsByType("sc")[0].getS();if(!a)throw Error('Error initializing satellite "s" for Adobe analytics \ud83d\ude1f');var b=[],d={};n.forEach(function(a){var e=d[a.asin]=1+(d[a.asin]||0);(b[e-1]=b[e-1]||[]).push(a)});a.products=a.products?a.products+",":"";b.forEach(function(b){a.events=a.apl(a.events,"event181",",",1);a.products+=b.map(function(a){return";"+a.asin+";;;event181\x3d1;eVar174\x3d"+[a.asin,a.widget,a.slotId,a.position,a.faceOut,a.ref,a.source,u,t].join(".")}).join(",");
c._satellite.notify(a.products,1);a.t();a.events=a.products=""});n=[]},500);return{scanForImpressions:q}});"use strict";g.when("refMarkers","live").execute(function(k,d){var g=c.console&&console.warn&&function(d){console.warn(d)}||function(){};d("click",".adbl-ref-marker-on-click",function(d){d=this.getAttribute("data-ref-marker-feature-code");if(null===d||""===d)d=this.getAttribute("refMarkerFeatureCode"),null===d||""===d?d=f:g('"refMarkerFeatureCode" attribute is deprecated, use semantically correct "data-ref-marker-feature-code" instead');
var c=this.getAttribute("data-ref-marker-counter");if(null===c||""===c)c=this.getAttribute("refMarkerCounter"),null===c||""===c?c=f:g('"refMarkerCounter" attribute is deprecated, use semantically correct "data-ref-marker-counter" instead');k.buildAndPost(d,this,c)})});"use strict";var h="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(c){return typeof c}:function(c){return c&&"function"===typeof Symbol&&c.constructor===Symbol&&c!==Symbol.prototype?"symbol":typeof c};g.register("refMarkers",
function(){var g={top:"t",center:"c",bottom:"b",left:"l",right:"r"},d={},l=c.console&&console.warn&&function(b){console.warn(b)}||function(){},e=c.console&&console.error&&function(b){console.error(b)}||function(){};d.record=function(b){l("refMarkers.record is deprecated in favor of buildAndPost");if(0<b.length&&(b=b.data("refmarker"),0<b.length)){b="/ajax-refmarker"+b;var a=new XMLHttpRequest;a.open("GET",b,!0);a.send(b)}};d.build=function(b,a,c){if(1>arguments.length)return l("build: feature code is required."),
"";var e=["a",d.buildPageCodeFromUrl()];a&&a.nodeName&&(a=d.getSlotNameFromElement(a));"string"===typeof a&&0<a.length&&e.push(d.abbreviateSlotName(a));("string"===typeof c&&0<c.length||"number"===typeof c)&&e.push(d.abbreviate(String(c),2));e.push(d.abbreviate(b,6));return e.join("_").slice(0,32)};d.getSlotNameFromElement=function(b){for(;b;){if(b.classList.contains("slot"))return b.id;b=b.parentElement}};d.buildAndPost=function(b,a,c,e){"function"===typeof c?(e=c,c=f):"function"===typeof a&&(e=
a,a=f);b=d.build.call(f,b,a,c);d.post(b,e)};d.buildAndRecord=function(){l("refMarkers.buildAndRecord is deprecated in favor of refMarkers.buildAndPost");d.buildAndPost.apply(f,arguments)};d._getWindowPathName=function(){return c.location.pathname};var p=void 0;d._isMobile=function(){p===f&&(p=!!document.querySelector("body \x3e .adbl-page.mobile"));return p};var w=void 0,x=void 0,r=/^\/*$/;d.buildPageCodeFromUrl=function(){var b=d._getWindowPathName();x!==b&&(x=b,b=b.replace(/\/ref[^&]+/g,""),r.test(b)&&
(b="home"),d._isMobile()&&(b="m_"+b),w=b&&d.abbreviate(b,16));return w};d.post=function(b,a){if(b&&b.length){var d="/ajax-refmarker"+(-1!==b.indexOf("?ref\x3d")?"":"?ref\x3d")+b,c=new XMLHttpRequest;c.open("GET",d,!0);c.onload=function(){a&&a(!0)};c.onerror=function(){a&&a(!1);e("refMarker ["+b+"] post: error")};c.send()}else a&&a(!1),e("refMarker ["+b+"] post: invalid refMarker")};var t=/(?:_)+/,u=/^[^A-Za-z\u00C0-\u00DE\u00DF-\u024F0-9]+|[^A-Za-z\u00C0-\u00DE\u00DF-\u024F0-9]+$/g,n=/[^A-Za-z\u00C0-\u00DE\u00DF-\u024F0-9]|([a-z\u00DF-\u00FF\u0101\u0103\u0105\u0107\u0109\u010B\u010D\u010F\u0111\u0113\u0115\u0117\u0119\u011B\u011D\u011F\u0121\u0123\u0125\u0127\u0129\u012B\u012D\u012F\u0131\u0133\u0135\u0137\u0138\u013A\u013C\u013E\u0140\u0142\u0144\u0146\u0148\u0149\u014B\u014D\u014F\u0151\u0153\u0155\u0157\u0159\u015B\u015D\u015F\u0161\u0163\u0165\u0167\u0169\u016B\u016D\u016F\u0171\u0173\u0175\u0177\u017A\u017C\u017E\u017F])([A-Z\u00C0-\u00DE\u0100\u0102\u0104\u0106\u0108\u010A\u010C\u010E\u0110\u0112\u0114\u0116\u0118\u011A\u011C\u011E\u0120\u0122\u0124\u0126\u0128\u012A\u012C\u012E\u0130\u0132\u0134\u0136\u0139\u013B\u013D\u013F\u0141\u0143\u0145\u0147\u014A\u014C\u014E\u0150\u0152\u0154\u0156\u0158\u015A\u015C\u015E\u0160\u0162\u0164\u0166\u0168\u016A\u016C\u016E\u0170\u0172\u0174\u0176\u0178\u0179\u017B\u017D])|([A-Za-z\u00C0-\u00DE\u00DF-\u024F])([0-9])|([0-9])([A-Za-z\u00C0-\u00DE\u00DF-\u024F])/g,
q=/[aeiouy\u00C0\u00C1\u00C2\u00C3\u00C4\u00C5\u00C6\u00C8\u00C9\u00CA\u00CB\u00CC\u00CD\u00CE\u00CF\u00D1\u00D2\u00D3\u00D4\u00D5\u00D6\u00D8\u00D9\u00DA\u00DB\u00DC\u00DD\u00E0\u00E1\u00E2\u00E3\u00E4\u00E5\u00E6\u00E8\u00E9\u00EA\u00EB\u00EC\u00ED\u00EE\u00EF\u00F0\u00F2\u00F3\u00F4\u00F5\u00F6\u00F8\u00F9\u00FA\u00FB\u00FC\u00FD\u00FF\u0100\u0101\u0102\u0103\u0104\u0105\u0112\u0113\u0114\u0115\u0116\u0117\u0118\u0119\u011A\u011B\u0128\u0129\u012A\u012B\u012C\u012D\u012E\u012F\u0130\u0131\u014C\u014D\u014E\u014F\u0150\u0151\u0152\u0153\u0168\u0169\u016A\u016B\u016C\u016D\u016E\u016F\u0170\u0171\u0172\u0173\u0176\u0177\u0178]([^aeiouy\u00C0\u00C1\u00C2\u00C3\u00C4\u00C5\u00C6\u00C8\u00C9\u00CA\u00CB\u00CC\u00CD\u00CE\u00CF\u00D1\u00D2\u00D3\u00D4\u00D5\u00D6\u00D8\u00D9\u00DA\u00DB\u00DC\u00DD\u00E0\u00E1\u00E2\u00E3\u00E4\u00E5\u00E6\u00E8\u00E9\u00EA\u00EB\u00EC\u00ED\u00EE\u00EF\u00F0\u00F2\u00F3\u00F4\u00F5\u00F6\u00F8\u00F9\u00FA\u00FB\u00FC\u00FD\u00FF\u0100\u0101\u0102\u0103\u0104\u0105\u0112\u0113\u0114\u0115\u0116\u0117\u0118\u0119\u011A\u011B\u0128\u0129\u012A\u012B\u012C\u012D\u012E\u012F\u0130\u0131\u014C\u014D\u014E\u014F\u0150\u0151\u0152\u0153\u0168\u0169\u016A\u016B\u016C\u016D\u016E\u016F\u0170\u0171\u0172\u0173\u0176\u0177\u0178]*)$/;
d.abbreviate=function(b,a){var d=b.replace(u,"");if(d){if(b=function(){var b="",c=d.replace(n,"$1$3$5_$2$4$6").split(t);c.length>a&&(c=c.slice(0,a));var e=Math.floor(a/c.length),f=a-e*c.length;c.forEach(function(a){a.length<e&&(f+=e-a.length)});c.forEach(function(a,c){b+=c?a[0].toUpperCase():a[0].toLowerCase();a=a.slice(1);c=e-1;f&&a.length>c&&(f--,c++);for(;a.length>c;)a=q.test(a)?a.replace(q,"$1"):a.slice(0,c);a.length&&(b+=a.toLowerCase())});return{v:b}}(),"object"===("undefined"===typeof b?"undefined":
h(b)))return b.v}else return l("refMarkers.abbreviate failed, possibly due to non-latin character set. returning empty string."),""};d.abbreviateSlotName=function(b){if(!b)return"";var a=b.split("-"),c=g[a[0]];return c!==f?c+a[1]:d.abbreviate(b,3)};return d})});
/* ******** */
(function(d){var f=window.AmazonUIPageJS||window.P,g=f._namespace||f.attributeErrors,c=g?g("AudibleChexCoreAssets",""):f;c.guardFatal?c.guardFatal(d)(c,window):c.execute(function(){d(c,window)})})(function(d,f,g){d.when("AudiblejQuery","ready").register("ajaxInitiator",function(c){function d(a){if("undefined"===typeof a)throw new b("No Data provided for ajax call");if("undefined"===typeof a.operation)throw new b("No method or operation provided in caller data for Ajax call ");if("undefined"===typeof a.targetDiv)throw new b("No target Div provided in caller data for Ajax call ");
if("undefined"===typeof a.url)throw new b("No url provided in caller data for Ajax call "+a.operation);if("undefined"===typeof a.dataType)throw new b("No response format provided in caller data for Ajax call "+a.operation);if("undefined"===typeof a.data)throw new b("No parameters provided in caller data for Ajax call "+a.operation);}function b(a){this.message=a;this.name="AjaxIOException"}return{initiateAjaxCall:function(a,b){try{d(a)}catch(n){console.log(n.message);return}"undefined"!==typeof b&&
"undefined"!==typeof b.preAjaxCallOperations&&b.preAjaxCallOperations(a.targetDiv);c.ajax({url:a.url,type:"POST",async:null!==a.async?a.async:!0,dataType:a.dataType,data:a.data,success:function(c){if("undefined"!==typeof b&&"undefined"!==typeof b.onAjaxSuccess)b.onAjaxSuccess(a.targetDiv,c)},error:function(c){if("undefined"!==typeof b&&"undefined"!==typeof b.onAjaxFailure)b.onAjaxFailure(a.targetDiv,c)},complete:function(c){if("undefined"!==typeof b&&"undefined"!==typeof b.onAjaxComplete)b.onAjaxComplete(a.targetDiv,
c)}})}}});"use strict";d.when("AudiblejQuery","StrictEvents","ready").register("countdownTimer",function(c,d){var b={existingCountDowns:{}},a=new d(["audibleCountdownTimerStarted","audibleCountdownTimerEnded"]);b.on=a.on.bind(a);b.off=a.off.bind(a);b._emit=a.emit.bind(a);var f=function(e,b){var a,d,f,l=c("#"+b);if(l){var h=l.data("includeSeconds")||!1;b=l.data("trimZeros")||!1;d=Math.floor(e/864E5);var m=864E5*d;a=Math.floor((e-m)/36E5);var g=36E5*a;f=0;var k=(e-m-g)/6E4;h?(h=Math.floor(k),f=Math.ceil((e-
m-g-6E4*h)/1E3),60===f&&(h++,f=0)):h=Math.ceil(k);60===h&&(a++,h=0);24===a&&(d++,a=0);e=d;d=h;k=l.data("timeFormat")||"{d}d {h}h {m}m {s}s";m=l.data("timeFormatHms")||"{h}h {m}m {s}s";g=l.data("timeFormatMs")||"{m}m {s}s";h=l.data("timeFormatS")||"{s}s";b&&("0"===e.toString()&&"0"===a.toString()&&"0"===d.toString()?k=h:"0"===e.toString()&&"0"===a.toString()?k=g:"0"===e.toString()&&(k=m));k=k.replace("{d}",e.toString()).replace("{h}",a.toString()).replace("{m}",d.toString()).replace("{s}",f.toString());
l.text(k)}else throw"Timer ID not found: "+b;},n=function(e,c){e in b.existingCountDowns?console.warn("Duplicate Timer ID detected: "+e):function(){b.existingCountDowns[e]={totalCountDown:c,elapsedMillis:0,startingTime:(new Date).getTime()};f(c,e);var d=b.existingCountDowns[e];a.emit("audibleCountdownTimerStarted",e);var g=setInterval(function(){d.elapsedMillis=(new Date).getTime()-d.startingTime;var c=d.totalCountDown-d.elapsedMillis;0>c?(clearInterval(g),f(0,e),delete b.existingCountDowns[e],a.emit("audibleCountdownTimerEnded",
e)):f(c,e)},1E3)}()};b.start=function(){c(".adbl-countdown-timer").length&&c(".adbl-countdown-timer").each(function(){var a=c(this).attr("id");if(null!==a){var b=c(this).data("duration");if(b===g)throw"Timer "+a+" does not specify a duration";n(a,b)}else throw"One or more timers do not have an id";})};b.getRemainingTime=function(a){return a in b.existingCountDowns?(a=b.existingCountDowns[a],a=a.totalCountDown-a.elapsedMillis,0<a?a:0):-1};return b})});
/* ******** */
(function(c){var d=window.AmazonUIPageJS||window.P,b=d._namespace||d.attributeErrors,a=b?b("AudibleAYCLBuyBoxAssets",""):d;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,d,b){c.when("AudiblejQuery","setReviewProductRatings","button","ready").execute(function(a,c,d){a(document).on("click",".adbl-buy-box-add-to-library",function(b){b.preventDefault();d.disable(a(this)[0]);a(this).find(".bc-button-text-inner").html(a("#adbl_web_buybox_adding_to_library").data("value"));
var e=a(this).attr("id");b=a("#csrfToken-"+e).val();a.ajax({url:"/a/pd/addToLibrary",data:{asin:e,csrfToken:b},success:function(b){a("#adbl-member-buy-box-"+e).parent().parent().parent().replaceWith(b);c.setReviewProductRatings(".asinForRatingStars",".adbl-prod-rate-review-bar-group",".adbl-prod-rate-review-bar",".adbl-prod-rate-review-bar-overall",".adbl-prod-rate-review-bar-performance",".adbl-prod-rate-review-bar-story")}});"undefined"!==typeof digitalData.product&&digitalData.product?digitalData.product[0].productInfo.productID=
e:digitalData.product=[{productInfo:{productID:e}}];_satellite.track("addToLibrary")})})});
/* ******** */
(function(d){var a=window.AmazonUIPageJS||window.P,c=a._namespace||a.attributeErrors,b=c?c("AudibleBrickCitySharedAssets",""):a;b.guardFatal?b.guardFatal(d)(b,window):b.execute(function(){d(b,window)})})(function(d,a,c){d.when("AudiblejQuery","modal","ratingStarsInit","ready").execute(function(b,d,a){var c,e,f;b(".review-ineligible-trigger").on("click",function(a){c=b(a.currentTarget).attr("data-star-count");e=b(a.currentTarget).find(".bc-rating-stars");f=b(a.currentTarget).find(".bc-tooltip");digitalData.libraryAsin=
a.currentTarget.getAttribute("asin");_satellite.track("audible.review.ineligible")});b(".review-ineligible-modal.bc-modal-closeable").on("click",function(){e&&0<e.size()&&(a.setStarCount(c,e[0]),f.addClass("bc-hidden"))})})});
/* ******** */
(function(k){var n=window.AmazonUIPageJS||window.P,q=n._namespace||n.attributeErrors,a=q?q("AudibleBuyBoxAssets",""):n;a.guardFatal?a.guardFatal(k)(a,window):a.execute(function(){k(a,window)})})(function(k,n,q){k.when("AudiblejQuery","ajaxInitiator","refMarkers","ready").execute(function(a,b,c){function f(a){var b=a.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");b.find(".adblBuyBoxCartErrorAlert").addClass("bc-hidden");b.find(".adblBuyBoxAddToWishlistErrorAlert").addClass("bc-hidden");b.find(".adblBuyBoxRemoveFromWishlistErrorAlert").addClass("bc-hidden");
b.addClass("bc-hidden");a=a.find(".adblAddToCartButton");a.addClass("bc-button-disabled");a.find(".adblAddToCartText").addClass("bc-hidden");a.find(".adblAddingText").removeClass("bc-hidden");a.unbind("click")}function g(b,d){d=b.find(".adblGoToCartButton");b.find(".adblAddToCartButton").addClass("bc-hidden");d.removeClass("bc-hidden");if(l)l.incrementCartCount();else if((b=a("header .bc-icon-cart"))&&1===b.length){d=a("span.cart-num");var c;0===d.length?(c=0,d=a("\x3cspan\x3e"),d.addClass("cart-num"),
b.parent().parent().append(d)):c=parseInt(d.text(),10);d.html(c+1)}}function e(a,b){b=a.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");b.find(".adblBuyBoxCartErrorAlert").removeClass("bc-hidden");b.removeClass("bc-hidden");a=a.find(".adblAddToCartButton");a.click(m);a.find(".adblAddingText").addClass("bc-hidden");a.find(".adblAddToCartText").removeClass("bc-hidden");a.removeClass("bc-button-disabled")}function h(a,b){}function m(p){p=a(p.target).closest(".adblAddToCart");var d={},l={};d.url=
"/cart/add";d.operation="ADD_TO_CART";d.dataType="json";d.targetDiv=p;l.asin=p.find('input[name\x3d"asin"]').val();l.token=p.find('input[name\x3d"token"]').val();l.key=p.find('input[name\x3d"key"]').val();l.tr=p.find('input[name\x3d"tr"]').val();l.ct=p.find('input[name\x3d"ct"]').val();d.data=l;l={};l.preAjaxCallOperations=f;l.onAjaxSuccess=g;l.onAjaxFailure=e;l.onAjaxComplete=h;"undefined"!==typeof digitalData.product&&digitalData.product?digitalData.product[0].productInfo.productID=d.data.asin:
digitalData.product=[{productInfo:{productID:d.data.asin}}];"undefined"!==typeof _satellite&&_satellite&&_satellite.track("cartAdd");b.initiateAjaxCall(d,l);c.buildAndPost("cartAdd",p[0])}a(".adblAddToCartButton").click(m);a(".adblBuyForButton").click(function(){"undefined"!==typeof _satellite&&_satellite&&_satellite.track("cartAdd")});a(".adblBuyForLink").on("click",function(a){a.preventDefault();"undefined"!==typeof _satellite&&_satellite&&_satellite.track("cartAdd");this.closest("form").submit()});
var l;k.when("headerCart").execute(function(a){l=a})});"use strict";k.when("AudiblejQuery","wishlistUtil","ajaxInitiator","refMarkers","ready").execute(function(a,b,c,f){function g(a){b.hideAllErrorMessages(a);a=a.find(".adblAddToWishlistButton, .adblAddToWishlistLink");b.showInterStateText(a,".adblAddingToWishlistText",".adblAddToWishlistText")}function e(a,d){d=a.find(".adblGoToWishlistButton, .adblGoToWishlistLink, .adblRemoveFromWishlistButton, .adblRemoveFromWishlistLink");a=a.find(".adblAddToWishlistButton, .adblAddToWishlistLink");
b.changeClickableStateOnSuccess(a,d,".adblRemovingFromWishlistText",".adblRemoveFromWishlistText")}function h(a,d){b.displayErrorMessageOnFailure(a,".adblBuyBoxAddToWishlistErrorAlert");a=a.find(".adblAddToWishlistButton, .adblAddToWishlistLink");a.click(l);b.changeClickableStateOnFailure(a,".adblAddingToWishlistText",".adblAddToWishlistText")}function m(a,b){}function l(p){var d=a(p.target).closest(".wishlist"),d=b.buildWishlistCaller(d,"/wish-list/add","ADD_TO_WISHLIST"),l=b.buildWishlistCallback(g,
e,h,m);"undefined"!==typeof digitalData.product&&digitalData.product?digitalData.product[0].productInfo.productID=d.data.asin:digitalData.product=[{productInfo:{productID:d.data.asin}}];var k=a(p.target).closest("button").attr("contentType");digitalData.clickedAsinContentType=k;"undefined"!==typeof _satellite&&_satellite&&_satellite.track("wishlistAddClick");c.initiateAjaxCall(d,l);f.buildAndPost("wishlistAddClick",p.target)}a(".adblAddToWishlistButton, .adblAddToWishlistLink").click(l)});"use strict";
k.when("AudiblejQuery","wishlistUtil","ajaxInitiator","refMarkers","ready").execute(function(a,b,c,f){function g(a){b.hideAllErrorMessages(a);a=a.find(".adblRemoveFromWishlistButton, .adblRemoveFromWishlistLink");b.showInterStateText(a,".adblRemovingFromWishlistText",".adblRemoveFromWishlistText")}function e(a,d){d=a.find(".adblAddToWishlistButton, .adblAddToWishlistLink");a=a.find(".adblGoToWishlistButton, .adblGoToWishlistLink, .adblRemoveFromWishlistButton, .adblRemoveFromWishlistLink");b.changeClickableStateOnSuccess(a,
d,".adblAddingToWishlistText",".adblAddToWishlistText")}function h(a,d){b.displayErrorMessageOnFailure(a,".adblBuyBoxRemoveFromWishlistErrorAlert");a=a.find(".adblRemoveFromWishlistButton, .adblRemoveFromWishlistLink");a.click(l);b.changeClickableStateOnFailure(a,".adblRemovingFromWishlistText",".adblRemoveFromWishlistText")}function m(a,b){k.now("WishlistAssets").execute(function(a){null!==a&&a!==q&&a.handleRemoveFromWishlist()})}function l(l){var d=a(l.target).closest(".wishlist"),k=b.buildWishlistCaller(d,
"/wish-list/remove","REMOVE_FROM_WISHLIST"),t=b.buildWishlistCallback(g,e,h,m),d=d.find("[data-asin]");digitalData.clickedAsin=d.data("asin");digitalData.clickedAsinContentType=d.data("content-type");"undefined"!==typeof _satellite&&_satellite&&_satellite.track("wishlistRemoveClick");c.initiateAjaxCall(k,t);f.buildAndPost("wishlistRemoveClick",l.target)}a(".adblRemoveFromWishlistButton, .adblRemoveFromWishlistLink").click(l)});"use strict";k.when("AudiblejQuery","ready").register("wishlistUtil",function(a){return{buildWishlistCaller:function(a,
c,f){var g={},e={};g.url=c;g.operation=f;g.dataType="json";g.targetDiv=a;e.asin=a.find('input[name\x3d"asin"]').val();e.token=a.find('input[name\x3d"token"]').val();e.key=a.find('input[name\x3d"key"]').val();g.data=e;return g},buildWishlistCallback:function(a,c,f,g){var e={};e.preAjaxCallOperations=a;e.onAjaxSuccess=c;e.onAjaxFailure=f;e.onAjaxComplete=g;return e},hideAllErrorMessages:function(a){a=a.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");a.find(".adblBuyBoxCartErrorAlert").addClass("bc-hidden");
a.find(".adblBuyBoxAddToWishlistErrorAlert").addClass("bc-hidden");a.find(".adblBuyBoxRemoveFromWishlistErrorAlert").addClass("bc-hidden");a.addClass("bc-hidden")},showInterStateText:function(a,c,f){a.addClass("bc-button-disabled");a.find(f).addClass("bc-hidden");a.find(c).removeClass("bc-hidden")},changeClickableStateOnSuccess:function(a,c,f,g){a.addClass("bc-hidden");c.find(f).addClass("bc-hidden");c.find(g).removeClass("bc-hidden");c.removeClass("bc-button-disabled");c.removeClass("bc-hidden")},
displayErrorMessageOnFailure:function(a,c){a=a.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");a.find(c).removeClass("bc-hidden");a.removeClass("bc-hidden")},changeClickableStateOnFailure:function(a,c,f){a.find(c).addClass("bc-hidden");a.find(f).removeClass("bc-hidden");a.removeClass("bc-button-disabled")}}});"use strict";k.when("AudiblejQuery","refMarkers","focus","Spinner","button","modal","parentalControls","ready").execute(function(a,b,c,f,g,e,h){function m(a){switch(a){case "desktop":a=
"dt";break;case "mobile":a="mb";break;case "tablet":a="tb";break;default:a="tb"}return a}function l(a){return c.change({focusElement:a.find("button:eq(0)").get(0)||a.get(0)})}function p(b){var d=a(b.evt.target).closest(".adblBuyBoxArea"),c=d.find(".adblCalltoActionContainer").first(),d=d.find(b.id);d.addClass("buyBoxCurrentAction").slideDown(l(d));c.slideUp();"undefined"!==typeof _satellite&&_satellite&&_satellite.track(b.tracker)}function d(b){var d=a(b.evt.target).closest(".adblBuyBoxArea"),c=d.find(".adblCalltoActionContainer");
b=d.find(b.id);c.slideDown(l(c));b.removeClass("buyBoxCurrentAction").slideUp()}function F(a){"undefined"!==typeof digitalData.product&&digitalData.product?digitalData.product[0].productInfo.buyNowType=a:digitalData.product=[{productInfo:{buyNowType:a}}]}function t(d,l,f,p,v){if(d.find("button").is(":disabled"))return!1;var k=d.get(0),t=k.querySelector(".bc-button-text-inner"),q=t.textContent,x=k.querySelector(".bc-button-text").dataset;v=x.loading;var r=void 0;v?(g.disable(k),t.textContent=v):r=
n(p,d);F(l);b.post(f+m(a(".deviceType").val()));"undefined"!==typeof _satellite&&_satellite&&_satellite.track(l);var u=k.closest("form"),K=function(){g.enable(k);t.textContent=q;r&&r.stop()},D=function(){return h.canPurchaseProceed(function(a){a?u.submit():K()})};v&&x.showConfirmModal?function(){var b=document.getElementById("confirm-modal"),d=function(){e.open(b);c.change({focusElement:b.querySelector(c.FOCUSABLE_SELECTOR),isFocusOnLayer:!0})};x.modalInit?d():a.ajax({url:"/order-lookup/asin",method:"POST",
contentType:"application/json",data:JSON.stringify({asins:[u.elements.asin.value],token:u.elements.token.value,key:u.elements.key.value}),dataType:"json",success:function(a){a.url?(x.modalInit="true",document.getElementById("adbl-review-previous-order-button").querySelector(".bc-button-text").setAttribute("href",a.url),document.getElementById("adbl-place-new-order-button").addEventListener("click",D),b.querySelector(".modal-close").addEventListener("click",K),b.addEventListener("click",function(a){a.target.classList.contains("bc-modal-closeable")&&
K()}),d()):D()}}).fail(D)}():D();return!1}function n(a,b){var d=f.DISPLAY_TYPE_DEFAULT;b.closest(".pdp-hero-buy-box").length&&(d=f.DISPLAY_TYPE_TRANSPARENT);a=new f(b.closest(a).get(0),d);a.start();return a}var q=void 0;k.when("tray").execute(function(a){return q=a});var r=!1;a("#discovery_buyBox_moreOptions").click(function(){r=!0});a("#discovery_buyBox_moreOptions_tray").find(".bc-trigger").click(function(){r=!1});a("#discovery_buyBox_moreOptions_modal").find(".bc-trigger").click(function(){r=!1});
a(".adblConfirmCreditPurchase").css("display","none").removeClass("bc-hidden");a(".adblConfirmCashPurchase").css("display","none").removeClass("bc-hidden");a(".adblConfirmEnterprisePurchase").css("display","none").removeClass("bc-hidden");a(".adblDiscoveryConfirmCreditPurchase").css("display","none").removeClass("bc-hidden");a(".adblDiscoveryConfirmCashPurchase").css("display","none").removeClass("bc-hidden");a(".adblBuyNowWithCredit").click(function(d){d={evt:d,id:".adblConfirmCreditPurchase",tracker:"buyNowCreditCartAddClick"};
b.post("1clk_bb_shw_bn_1crdt_"+m(a(".deviceType").val()));p(d)});a(".adblConfirmCreditCancelButton").click(function(c){d({evt:c,id:".adblConfirmCreditPurchase"});b.post("1clk_bb_cncl_crdt_cnfrm_"+m(a(".deviceType").val()))});a(".adblBuyNowCashButton").click(function(d){d={evt:d,id:".adblConfirmCashPurchase",tracker:"buyNowCashCartAddClick"};b.post("1clk_bb_shw_bn_cash_"+m(a(".deviceType").val()));a("channelLiteProduct").length&&b.post("1clk_bb_shw_audshw_add2lib4cash_"+m(a(".deviceType").val()));
var c=a(d.evt.target).closest(".adblBuyBoxArea"),l=c.find(".adblCalltoActionContainer").first();0===c.parent().find(".adblBuyBoxArea \x3e .adblConfirmCashPurchase").length&&l.after(c.find(d.id));p(d)});a(".adblConfirmCashCancelButton").click(function(c){d({evt:c,id:".adblConfirmCashPurchase"});b.post("1clk_bb_cncl_csh_cnfrm_"+m(a(".deviceType").val()));a("channelLiteProduct").length&&b.post("1clk_bb_cncl_audshw_cnfrm_"+m(a(".deviceType").val()))});a(".enterprisePurchaseButton").click(function(d){d=
{evt:d,id:".adblConfirmEnterprisePurchase",tracker:"enterpriseAddToLibraryClick"};b.post("1clk_bb_shw_ntprs_purchs_"+m(a(".deviceType").val()));p(d)});a(".adblConfirmEnterpriseCancelButton").click(function(c){d({evt:c,id:".adblConfirmEnterprisePurchase"});b.post("1clk_bb_cncl_ntprs_cnfrm_"+m(a(".deviceType").val()))});a(".adblDiscoveryBuyNowWithCreditButton").click(function(d){d={evt:d,id:".adblDiscoveryConfirmCreditPurchase",tracker:"buyNowCreditCartAddClick"};var c=a(d.evt.target).parent().attr("credit");
digitalData.creditPrice=c;b.post("1clk_bb_shw_bn_1crdt_"+m(a(".deviceType").val()));var c=a(d.evt.target).closest(".adblBuyBoxArea"),l=c.find(".adblCalltoActionContainer").first();0===c.parent().find(".adblBuyBoxArea \x3e .adblDiscoveryConfirmCreditPurchase").length&&l.after(c.find(d.id));p(d)});a(".adblDiscoveryConfirmCreditCancelButton").click(function(c){d({evt:c,id:".adblDiscoveryConfirmCreditPurchase"});b.post("1clk_bb_cncl_crdt_cnfrm_"+m(a(".deviceType").val()))});a(".adblConfirmCreditPurchaseButton").click(function(b){return t(a(this),
"buyNowCreditPurchase","1clk_bb_cnfrm_crdt_purchs_","#adbl-confirm-credit-purchase",b)});a(".adblConfirmCashPurchaseButton").click(function(d){d=t(a(this),"buyNowCashPurchase","1clk_bb_cnfrm_csh_purchs_","#adbl-confirm-cash-purchase",d);a("channelLiteProduct").length&&b.post("1clk_bb_cnfm_audshw_purchs_"+m(a(".deviceType").val()));return d});a(".adblDiscoveryConfirmCreditPurchaseButton").click(function(b){return t(a(this),"buyNowCreditPurchase","1clk_bb_cnfrm_crdt_purchs_","#adbl-confirm-credit-purchase",
b)});var u=document.getElementById("discovery_buyBox_moreOptions_modal");u&&a("#paymentsWidgetDialog").find(".bc-trigger").find(".bc-icon-close").click(function(a){r&&(a.preventDefault(),a.stopPropagation(),e.toggle(u))});var v=document.getElementById("discovery_buyBox_moreOptions_tray");v&&a("#paymentsWidgetDialog").find(".payments-widget-close-dialog").click(function(a){r&&(a.preventDefault(),a.stopPropagation(),q.toggle(v))})});"use strict";k.when("AudiblejQuery","ready").execute(function(a){var b=
["MobileJavaScriptBridge","AndroidJavaScriptBridge"],c=function(){for(var a=0;a<b.length;++a){var c=b[a];if("undefined"!==typeof n[c]&&n[c])return n[c]}return null};(function(){function b(a){if(m)return h.onBuyWithFreeTrialClicked(m),!1}function g(a){if(m)return h.onBuyWithCashClicked(m),!1}function e(a){a.preventDefault();a=n.location.origin;var b=document.getElementsByClassName("romanceTrialForm")[0].getAttribute("action");h.launchAudiblePageAfterSignIn(a+b+"\x26productAsin\x3d"+m+"\x26membershipAsin\x3d"+
l)}var h=c();if(h){var m=a("input[name\x3dproductAsin]").val()||a("input[name\x3dasin]").val(),l=a("input[name\x3dmembershipAsin]").val(),p=a("input[name\x3duseJSBridgeForRomanceAnonSignup]").val();m&&("function"===typeof h.onBuyWithFreeTrialClicked&&a(".adblTrialButton").each(function(d,c){a(c).click(b)}),p!==q&&"false"!==p||"function"!==typeof h.onBuyWithCashClicked||a(".adblBuyForButton, .adblBuyNowLogInButton, .adblBuyNowLogInLink").each(function(b,c){a(c).click(g)}),"true"===p&&"function"===
typeof h.launchAudiblePageAfterSignIn&&a(".adblRomanceTrialButton").each(function(b,c){a(c).click(e)}))}})()});"use strict";k.when("AudiblejQuery","toastMessage","specialPromo","refMarkers","ready").register("specialPromoBuyBoxCallBacks",function(a,b,c,f){function g(c){b(l,{duration:2E3});a("#sp-three-dot-menu-"+d).data("is-in-tray",!0);d=c.next(".spActionData").data("asin");a(".sp-add-to-selection-"+d).addClass("bc-pub-hidden");a(".sp-in-selection-"+d).removeClass("bc-pub-hidden")}function e(c){b(p,
{duration:2E3});(c=c.next(".spActionData").data("asin"))&&(d=c);a("#sp-three-dot-menu-"+d).data("is-in-tray",!1);a(".sp-add-to-selection-"+d).removeClass("bc-pub-hidden");a(".sp-in-selection-"+d).addClass("bc-pub-hidden")}var h=a("#add-to-tray-trigger"),m=a("#remove-from-tray-trigger"),l=a('input[name\x3d"addedToSaleToastMessage"]').val(),p=a('input[name\x3d"removedFromSaleToastMessage"]').val(),d,k;a(".mobile-sp-category-three-dot-menu").click(function(b){var c=a(b.currentTarget);c.data("is-in-tray")?
(h.addClass("bc-pub-hidden"),m.removeClass("bc-pub-hidden"),k=c.data("remove-url")):(h.removeClass("bc-pub-hidden"),m.addClass("bc-pub-hidden"),k=c.data("add-url"));d=c.data("asin");f.buildAndPost("moreOptions",b.currentTarget)});h.click(function(){c.cartHelper.addToCart(h,k,g);f.buildAndPost("add",h)});m.click(function(){c.cartHelper.removeFromCart(m,k,e);f.buildAndPost("remove",m)});return{addToSpecialPromoTrayCallBack:g,removeFromSpecialPromoTrayCallBack:e}});"use strict";k.when("AudiblejQuery",
"cloudPlayerLauncher","ready").execute(function(a,b){a(document).on("click",".adblBuyBoxListenNow",function(c){c.preventDefault();c=a(this).children(".bc-button-text").attr("asin");null!==c&&c!==q&&b.openCloudPlayer(c,"a_ownedbuybox_cloudplayer")})});"use strict";k.when("AudiblejQuery","geoRights","paymentsWidget","issuerIconUtility").execute(function(a,b,c,f){function g(c){if("undefined"===typeof c||null===c)a("#adbl-payment-instrument-details").addClass("bc-hidden"),a("#adbl-payment-invalid-instr-error").addClass("bc-hidden"),
a("#adbl-payment-geoblocked-instr-error").addClass("bc-hidden"),a("#adbl-payment-noInstr-error").removeClass("bc-hidden"),a(".adblConfirmCashPurchaseButton").hasClass("bc-button-disabled")||(a("#adbl-confirm-cash-purchase-form").find('input[name\x3d"paymentId"]').val(""),m());else{var g=a("#adbl-confirm-cash-purchase-form");g.find('input[name\x3d"paymentId"]').val();var d=c.paymentId;c.isValid?b.validateGeoRights(g,c.billingAddressId).then(function(b){if(b){b=c.paymentId;var d=a("#adbl-payment-instrument-details").find(".buy-box-issuer-icon");
f.updateImage(d.get(0),c);a("#adbl-payment-instrument-details").find(".adblCCTail").html(c.tail);a("#adbl-confirm-cash-purchase-form").find('input[name\x3d"paymentId"]').val(b);a("#adbl-payment-instrument-details").removeClass("bc-hidden");a("#adbl-payment-invalid-instr-error").addClass("bc-hidden");a("#adbl-payment-noInstr-error").addClass("bc-hidden");a("#adbl-payment-geoblocked-instr-error").addClass("bc-hidden");a(".adblConfirmCashPurchaseButton").hasClass("bc-button-disabled")&&h()}else e(c)},
function(){e(c)}):(a("#adbl-payment-instrument-details").addClass("bc-hidden"),a("#adbl-payment-noInstr-error").addClass("bc-hidden"),a("#adbl-payment-geoblocked-instr-error").addClass("bc-hidden"),a("#adbl-payment-invalid-instr-error").removeClass("bc-hidden"),a(".adblConfirmCashPurchaseButton").hasClass("bc-button-disabled")||m(),a("#adbl-confirm-cash-purchase-form").find('input[name\x3d"paymentId"]').val(d))}}function e(b){b=b.paymentId;a("#adbl-payment-instrument-details").addClass("bc-hidden");
a("#adbl-payment-noInstr-error").addClass("bc-hidden");a("#adbl-payment-invalid-instr-error").addClass("bc-hidden");a("#adbl-payment-geoblocked-instr-error").removeClass("bc-hidden");a(".adblConfirmCashPurchaseButton").hasClass("bc-button-disabled")||(a("#adbl-confirm-cash-purchase-form").find('input[name\x3d"paymentId"]').val(b),m())}function h(){a(".adblConfirmCashPurchaseButton").removeClass("bc-button-disabled");a(".adblConfirmCashPurchaseButton").find("button").prop("disabled",!1)}function m(){a(".adblConfirmCashPurchaseButton").addClass("bc-button-disabled");
a(".adblConfirmCashPurchaseButton").find("button").prop("disabled",!0)}a(".changePaymentInstr").click(function(a){a.preventDefault();c.openPaymentsWidgetView(c.PAYMENTS_LIST_VIEW_NAME)});a(".addnewAddress").click(function(a){a.preventDefault();c.openPaymentsWidgetView(c.ADD_ADDRESS_VIEW_NAME)});c.on("addAddress",function(c,e){if("undefined"!==typeof e&&null!==e&&!1!==e.success){var d=e.addressId;if("undefined"===typeof d||null===d)return null;var f=a(".buyBoxCurrentAction #adbl-address-error");b.validateGeoRights(f,
d).then(function(b){b?(f.addClass("bc-hidden"),a(".adblConfirmCashPurchaseButton").hasClass("bc-button-disabled")&&h(),a(".adblConfirmCreditPurchaseButton").hasClass("bc-button-disabled")&&(a(".adblConfirmCreditPurchaseButton").removeClass("bc-button-disabled"),a(".adblConfirmCreditPurchaseButton").find("button").prop("disabled",!1)),a("#adbl-confirm-credit-purchase-form").find('input[name\x3d"addressId"]').val(d),a("#adbl-confirm-cash-purchase-form").find('input[name\x3d"addressId"]').val(d)):n.location.reload()},
function(){n.location.reload()})}});c.on("confirmSelectedPayment",function(a,b){"undefined"!==typeof b&&null!==b&&g(b.paymentInstrument)});c.on("addPayment",function(a,b){"undefined"!==typeof b&&null!==b&&b.success&&c.isPaymentsWidgetDialogOpen()&&g(b.paymentInstrument)})});"use strict";k.when("AudiblejQuery","ajaxInitiator","ready").register("geoRights",function(a,b){function c(b){return new Promise(function(c,e){a.ajax({url:b.url,type:"POST",async:!0,dataType:b.dataType,data:b.data}).done(function(a){c(a.success)}).fail(function(a){e(!1)})})}
return{validateGeoRights:function(a,b){var e={},h={};e.url="/a/buy-box/validate";e.operation="VALIDATE_GEO_RIGHTS";e.dataType="json";e.targetDiv=a;a=a.parent().find("form");h.asin=a.find('input[name\x3d"asin"]').val();h.asin&&0!==h.asin.length||(h.asin=a.find('input[name\x3d"giftAsin"]').val());h.token=a.find('input[name\x3d"token"]').val();h.key=a.find('input[name\x3d"key"]').val();h.billingAddressId=b;e.data=h;return c(e)}}});"use strict";k.when("AudiblejQuery","setReviewProductRatings","ready").execute(function(a,
b){b.setReviewProductRatings(".asin-for-rating-stars",".ratings-csrf-token",".adbl-prod-rate-review-bar-group",".adbl-prod-rate-review-bar",".adbl-prod-rate-review-bar-overall",".adbl-prod-rate-review-bar-performance",".adbl-prod-rate-review-bar-story")});"use strict";k.when("AudiblejQuery","button","refMarkers","Spinner","minervaBridgeUtil","ready").execute(function(a,b,c,f,g){function e(a){a=new f(a.get(0),f.DISPLAY_TYPE_DEFAULT);a.start();return a}function h(a){a&&(a.stop(),a.remove())}function m(){a(".return-book-button").each(function(){b.disable(this)})}
function l(){a(".romance-add-to-library-button").each(function(){b.disable(this)})}function p(c){var d=a(".romance-add-to-library-button");h(c);d.each(function(){b.enable(this)})}function d(b,c){a.ajax({url:"/aycl-return-flow?asin\x3d"+b,type:"GET",success:function(b){0===a("#return-flow-view").length&&(a("body").append(b),J&&J(document.getElementById("return-flow-view")));a(".return-book-button").off("click").on("click",C(c));a("#cancel-return-flow-button").off("click").on("click",t(c));z();F();
a("#return-form, input[type\x3dradio]").attr("checked",!1)},error:function(){G();p(c)}})}function F(){a("#return-form, input:checked").change(function(){a(".return-book-button").each(function(){b.enable(this)})})}function t(d){return function(e){a(".return-book-button").each(function(){b.disable(this)});if(g)g.onReturnFlowPresented(w.CANCELLED,"","",-1);z();p(d);c.buildAndPost("returnflowCancelClick",e.target)}}function C(b){return function(d){if(!a(".return-book-button").hasClass("bc-button-disabled")){H(a("#return-flow-view-alert"));
m();var e=a("input[name\x3daudiobook]:checked").val();if(null!==e){c.buildAndPost("returnflowReturnBookClick",d.target);d=a("#order-num-"+e).val();var h=a("#hmac-"+e).val();E(e,d,h,b)}}}}function E(b,c,d,e){c={orderNum:c,hmac:d};var h=(new Date).getTime();a.ajax({url:v(b,c),type:"DELETE",dataType:"json",success:function(){r(b,h,e)},error:function(){var c=(new Date).getTime()-h;if(g)g.onReturnFlowPresented(w.FAILED,b,"",c);a("#return-flow-view-alert").removeClass("bc-hidden");p(e)}})}function r(b,
c,d){var e=a("#book-to-add").val(),h=a("#book-to-add-hmac").val();u(e,h,"adbl_rom_ar_rf_atl",function(){var a=(new Date).getTime()-c;if(g)g.onReturnFlowPresented(w.SUCCESS,b,e,a);z();A()},function(h){h=h.responseJSON;if(h!==q&&!0===h.limit_reached)a("input[value\x3d"+b+"]").closest("li").remove();else{h=(new Date).getTime()-c;if(g)g.onReturnFlowPresented(w.FAILED,b,e,h);G();p(d)}})}function u(b,c,d,e,h){a.ajax({url:v(b,{hmac:c,ref:d}),type:"POST",dataType:"json",success:e,error:h})}function v(b,c){if(null===
c||c===q)c={};c=a.param(c);return["/library/audiobook/"+b,c].join("?")}function z(){I.toggle(document.getElementById("return-flow-view"))}function G(){y.find(".adblBuyBoxRomanceAYCLErrorAlert").removeClass("bc-hidden");y.removeClass("bc-hidden")}function H(a){a.addClass("bc-hidden")}function L(){var a=B("getAppModalWidgetType"),b=n.location,c=n.location.href.replace(n.location.search,""),d="?";a.getAppModalWidgetType="ROMANCE";for(var e in a)a.hasOwnProperty(e)&&(d+=e+"\x3d"+a[e]+"\x26");b.href=c+
d}function A(){x?setTimeout(function(){L()},x):L()}function B(a){var b={};n.location.search.slice(1).split("\x26").map(function(a){return a.split("\x3d")}).reduce(function(b,c){var d=c[0];c=c[1];d&&0!==d.length&&d!==a&&(b[decodeURIComponent(d)]=decodeURIComponent(c));return b},b);return b}var w={SUCCESS:"SUCCESS",FAILED:"FAILURE",CANCELLED:"CANCEL"},y=null,x=void 0,I=null,J=null;k.when("tray","mobile").execute(function(a){I=a;J=a.init});k.when("modal","desktop").execute(function(a){I=a});a(".romance-add-to-library-button").on("click",
function(b){l();var h=b.target,f=a(h).closest("div[name\x3d'romance-add-to-library-form']"),m=f.find("input[name\x3d'asin']").val(),v=f.find("input[name\x3d'token']").val(),k=f.find("input[name\x3d'ref']").val(),z=(new Date).getTime();x=parseInt(f.find("input[name\x3d'delay']").val(),10)||0;y=a(h).closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");var n=e(f);H(y.find(".adblBuyBoxRomanceAYCLErrorAlert"));H(y);u(m,v,k,function(){var a=(new Date).getTime()-z;if(g)g.onAddToLibrary(w.SUCCESS,m,a);
A()},function(a){a=a.responseJSON;if(a!==q&&!0===a.limit_reached)d(a.asin,n),c.buildAndPost("returnflowLaunched",b.target);else{G();a=(new Date).getTime()-z;if(g)g.onAddToLibrary(w.FAILED,m,a);p(n)}})});m()});"use strict";k.when("AudiblejQuery","countdownTimer").execute(function(a,b){function c(a){a.closest(".adblBuyBoxContainer").find(".adblBuyNowCashButton, .adblBuyNowWithCredit").off("click").on("click",function(){var a=f();a.cic="se";a.ref="a_bb_cic_se";var b=n.location.href.replace(n.location.search,
""),c="?",g;for(g in a)a.hasOwnProperty(g)&&(c+=g+"\x3d"+a[g]+"\x26");n.location.href=b+c})}function f(){var a={};n.location.search.slice(1).split("\x26").map(function(a){return a.split("\x3d")}).reduce(function(a,b){var c=b[0];b=b[1];c&&0!==c.length&&(a[decodeURIComponent(c)]=decodeURIComponent(b));return a},a);return a}b.start();b.on("audibleCountdownTimerEnded",function(b,e){b=a("#"+e);b.hide();e=b.closest(".adblSaleTimerContainer");e.find(".adblSaleHasEnded").show();e.find(".adblSaleEndsIn").hide();
c(b)})});"use strict";k.when("AudiblejQuery","cloudPlayerLauncher","minervaBridgeUtil","refMarkerCommonUtil","ready").execute(function(a,b,c,f){function g(a,b){var c=b.getAttribute("asin"),f=b.getAttribute("contentType");b=b.getAttribute("asinListIndex");"undefined"!==typeof digitalData&&digitalData&&(digitalData.clickedAsin=c,digitalData.clickedAsinContentType=f,b&&(digitalData.clickedAsinListIndex=parseInt(b,10)+1),"undefined"!==typeof _satellite&&_satellite&&_satellite.track(a))}a(document).on("click",
".adblBuyBoxMinervaPlayNow",function(e){e.preventDefault();f.sendRefMarker("_1clk_bb_pl_",a(".deviceType").val());g("oneClickPlay",a(this)[0].querySelector('button[name\x3d"playButton"]'));if(null===c){var h=a(this).children(".bc-button-text");e=h.attr("asin");h=h.attr("contentDeliveryType");null!==e&&e!==q&&b.openCloudPlayer(e,"a_minerva_cloudplayer_[ASIN]".replace("[ASIN]",e),{contentDeliveryType:h})}});a(document).on("click",".adblBuyBoxMinervaPlayNowConsumable",function(e){e.preventDefault();
if(null===c){var h=a(this);e=h.attr("asin");h=h.attr("contentDeliveryType");null!==e&&e!==q&&b.openCloudPlayer(e,"a_minerva_cloudplayer_[ASIN]".replace("[ASIN]",e),{contentDeliveryType:h})}});a(document).on("click",".adblBuyBoxMinervaPause",function(b){b.preventDefault();f.sendRefMarker("_1clk_bb_ps_",a(".deviceType").val());g("oneClickPause",a(this)[0].querySelector('button[name\x3d"pauseButton"]'))})});"use strict";k.when("AudiblejQuery","minervaBridgeUtil","modal","ready").execute(function(a,b,
c){function f(a,e,f){if(b.on1ClickPlayButtonAction){if(f=e.getAttribute("asin"),e=e.getAttribute("contentDeliveryType"),f)b.on1ClickPlayButtonAction(a,f,e,!1,null)}else c.toggle(f)}function g(){return function(a,b,c){c=document.getElementsByClassName("adblBuyBoxMinervaPlayNow");for(var f=0;f<c.length;f++){var d=c[f].parentElement,g=c[f],k=d.querySelector(".adblBuyBoxMinervaPause"),d=d.querySelector('button[name\x3d"playButton"]').getAttribute("asin");d!==q&&d===a&&b===e.PLAYING?(g.classList.contains("bc-hidden")||
g.classList.add("bc-hidden"),k.classList.contains("bc-hidden")&&k.classList.remove("bc-hidden")):(g.classList.contains("bc-hidden")&&g.classList.remove("bc-hidden"),k.classList.contains("bc-hidden")||k.classList.add("bc-hidden"))}}}if(b){var e={PLAYING:"PLAYING",PAUSED:"PAUSED"};b.on1ClickPlayButtonAction&&(b.onNativePlayerChangeState=g(),b.on1ClickPlayButtonAction("REGISTER",null,null,!1,null));a(document).on("click",".adblBuyBoxMinervaPlayNow",function(b){b.preventDefault();b=a(this)[0].querySelector('button[name\x3d"playButton"]');
var c=a(this).parent().find(".adblBuyBoxMinervaPlayNowNoJSBridgeModal")[0];f("PLAY",b,c)});a(document).on("click",".adblBuyBoxMinervaPause",function(b){b.preventDefault();b=a(this)[0].querySelector('button[name\x3d"pauseButton"]');var c=a(this).parent().find(".adblBuyBoxMinervaPlayNowNoJSBridgeModal")[0];f("PAUSE",b,c)});a(document).on("click",".adblBuyBoxMinervaPlayNowConsumable",function(b){b.preventDefault();b=a(this)[0];var c=a(this).parent().find(".adblBuyBoxMinervaPlayNowNoJSBridgeModal")[0];
f("PLAY",b,c)})}});"use strict";k.when("AudiblejQuery","modal","refMarkerCommonUtil","ready").execute(function(a,b,c){a(document).on("click",".adbl-buybox-review-ineligibility-alert",function(b){b.preventDefault();b=a(this)[0].querySelector('button[name\x3d"adblBuyBoxReviewAlertButton"]').getAttribute("asin");c.sendRefMarker("_1clk_bb_inlegrnr_",a(".deviceType").val());"undefined"!==typeof digitalData&&digitalData&&(digitalData.clickedAsin=b,"undefined"!==typeof _satellite&&_satellite&&_satellite.track("adblBuyBoxReviewIneligibleAlert"))})});
"use strict";k.when("AudiblejQuery","refMarkers","ready").execute(function(a,b){k.register("refMarkerCommonUtil",function(){var a={getAbbreviatedDeviceType:function(a){switch(a){case "desktop":a="dt";break;case "mobile":a="mb";break;case "tablet":a="tb";break;default:a="dt"}return a},sendRefMarker:function(f,g){"undefined"!==typeof digitalData&&digitalData&&digitalData.page&&digitalData.page.category&&digitalData.page.category.pageType?b.post(b.abbreviate(digitalData.page.category.pageType,3)+f+a.getAbbreviatedDeviceType(g)):
b.post("unk"+f+a.getAbbreviatedDeviceType(g))}};return a})});"use strict";k.when("AudiblejQuery","ready").register("minervaBridgeUtil",function(a){a=["MobileJavaScriptBridge","AndroidJavaScriptBridge","StoreHandler"];a:{for(var b=0;b<a.length;++b){var c=a[b];if("undefined"!==typeof n[c]&&n[c]){a=n[c];break a}}a=null}return a});"use strict";k.when("AudiblejQuery","minervaBridgeUtil","refMarkerCommonUtil","Spinner","button","ready").execute(function(a,b,c,f,g){function e(a){a.hasClass("bc-hidden")&&
a.removeClass("bc-hidden")}function h(a){a=new f(a.get(0),f.DISPLAY_TYPE_DEFAULT);a.start();return a}function k(a){a&&a instanceof f&&(a.stop(),a.remove())}function l(a,b){b=b.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");e(b.find(a));e(b)}function p(a,b){b=b.closest(".adblBuyBoxArea").find(".adblBuyBoxAjaxError");a=b.find(a);a.hasClass("bc-hidden")||a.addClass("bc-hidden");b.hasClass("bc-hidden")||b.addClass("bc-hidden")}function d(b){a(b).each(function(a,b){g.disable(b)})}function n(b){a(b).each(function(a,
b){g.enable(b)})}function q(c){var e=a(c.target).closest(c.data.form),f=e.find(c.data.buttonCssClass);if(g.isButtonDisabled(f.get(0)))return!1;var t=c.data.errorAlertCssClass,r=e.find("input[name\x3d'asin']").val(),A=parseInt(e.find("input[name\x3d'delay']").val(),10)||0,B=(new Date).getTime(),w=a(c.data.buttonCssClass).filter(function(a,b){return!g.isButtonDisabled(b)});d(w);p(t,e);var y=h(e);"undefined"!==typeof digitalData.product&&digitalData.product?digitalData.product[0].productInfo.productID=
r:digitalData.product=[{productInfo:{productID:r}}];"undefined"!==typeof _satellite&&_satellite&&_satellite.track("addToLibrary");C(e,"POST",function(){E(A);if(b)b.onAddToLibrary(u.SUCCESS,r,(new Date).getTime()-B)},function(a){l(t,e);k(y);n(w);if(b)b.onAddToLibrary(u.FAILURE,r,(new Date).getTime()-B)})}function C(b,c,d,e){var f=b.find("input[name\x3d'asin']").val(),g=b.find("input[name\x3d'token']").val();b=b.find("input[name\x3d'ref']").val();a.ajax({url:r(f,{hmac:g,ref:b}),type:c,dataType:"json",
success:d,error:e})}function E(a){setTimeout(function(){location.reload(!0)},a)}function r(b,c){c=a.param(c||{});return["/library/audiobook/"+b,c].join("?")}var u={SUCCESS:"SUCCESS",FAILED:"FAILURE"};a(".discovery-add-to-library-button").click({form:"div[name\x3d'discovery-add-to-library-form']",buttonCssClass:".discovery-add-to-library-button",errorAlertCssClass:".adblBuyBoxAddToLibraryErrorAlert"},q);a(".adblFollowPodcastButton").click({form:".adblFollowPodcast",buttonCssClass:".adblFollowPodcastButton",
errorAlertCssClass:".adblBuyBoxFollowPodcastErrorAlert"},q);a(".adblUnfollowPodcastButton").click({form:".adblFollowPodcast",buttonCssClass:".adblUnfollowPodcastButton",errorAlertCssClass:".adblBuyBoxUnfollowPodcastErrorAlert"},function(b){var e=a(b.target).closest(b.data.form),f=e.find(b.data.buttonCssClass),g=b.data.errorAlertCssClass,q=parseInt(e.find("input[name\x3d'delay']").val(),10)||0;d(f);p(g,e);var r=h(e);c.sendRefMarker("_1clk_bb_rvfmlib_",a(".deviceType").val());"undefined"!==typeof digitalData&&
digitalData&&(digitalData.clickedAsin=e.find("input[name\x3d'asin']").val(),"undefined"!==typeof _satellite&&_satellite&&_satellite.track("removeFromLibrary"));C(e,"DELETE",function(){E(q)},function(a){l(g,e);k(r);n(f)})})});"use strict";k.when("ready").register("parentalControls",function(){return{canPurchaseProceed:function(a){if(n.StoreHandler&&n.StoreHandler.onBuyAudiobookPressed){if(n.proceedCheckout)return a(!1);n.proceedCheckout=function(b){n.proceedCheckout=q;a(b)};n.StoreHandler.onBuyAudiobookPressed()}else return a(!0)}}});
"use strict";k.when("AudiblejQuery","minervaBridgeUtil","refMarkerCommonUtil","modal","ready").execute(function(a,b,c,f){function g(){return function(a,b){var c=document.querySelector(".adblBuyBoxMinervaSaveToLibrary"),f=document.querySelector(".adblBuyBoxMinervaViewInLibrary"),g=c.querySelector('button[name\x3d"saveToLibraryButton"]').getAttribute("asin");g!==q&&g===a&&b===h.SAVED_ON_LOCAL_DEVICE?e(c,f):(c.classList.contains("bc-hidden")&&c.classList.remove("bc-hidden"),f.classList.contains("bc-hidden")||
f.classList.add("bc-hidden"))}}function e(a,b){a.classList.contains("bc-hidden")||a.classList.add("bc-hidden");b.classList.contains("bc-hidden")&&b.classList.remove("bc-hidden")}if(b){var h={SAVED_ON_LOCAL_DEVICE:"SAVED_ON_LOCAL_DEVICE",NOT_ON_LOCAL_DEVICE:"NOT_ON_LOCAL_DEVICE"};if(b.getDownloadStatus&&b.downloadAsin){b.notifyDownloadStatus=g();var k=document.querySelector('button[name\x3d"saveToLibraryButton"]');k&&(k=k.getAttribute("asin"))&&b.getDownloadStatus(k)}a(document).on("click",".adblBuyBoxMinervaSaveToLibrary",
function(g){g.preventDefault();var h=a(this)[0].querySelector('button[name\x3d"saveToLibraryButton"]');g=h.getAttribute("asin");var d=h.getAttribute("contentType"),h=h.getAttribute("asinListIndex");c.sendRefMarker("_1clk_bb_svtlib_",a(".deviceType").val());"undefined"!==typeof digitalData&&digitalData&&(digitalData.clickedAsin=g,digitalData.clickedAsinContentType=d,h&&(digitalData.clickedAsinListIndex=parseInt(h,10)+1),"undefined"!==typeof _satellite&&_satellite&&_satellite.track("adblBuyBoxDwonlaodContent"));
if(b.downloadAsin){if(g=document.querySelector(".adblBuyBoxMinervaViewInLibrary"),d=this.querySelector('button[name\x3d"saveToLibraryButton"]').getAttribute("asin"))b.downloadAsin(d),e(this,g)}else f.toggle(a(this).parent().find(".adblBuyBoxMinervaSaveToLibraryNoJSBridgeModal")[0])})}});"use strict";k.when("AudiblejQuery","refMarkers","minervaBridgeUtil","ready").execute(function(a,b,c){a(".discovery-upsell-button").click(function(f){var g=a(f.target).parent(),e=g.data("asin"),h=g.data("native-login-enabled"),
g=g.attr("href");digitalData.clickedAsin=e;"undefined"!==typeof _satellite&&_satellite&&_satellite.track("membershipSignUp");b.buildAndPost("membershipSignUp",e);!0===h&&c&&c.launchAudiblePageAfterSignIn&&(f.preventDefault(),c.launchAudiblePageAfterSignIn(n.location.origin+g))})});"use strict";k.when("AudiblejQuery","minervaBridgeUtil","ready").execute(function(a,b){a(".rate-and-review-button").click(function(c){var f=a(c.target).parent(),g=f.data("native-login-enabled"),f=f.data("relative-href");
!0===g&&b&&b.launchAudiblePageAfterSignIn&&(c.preventDefault(),b.launchAudiblePageAfterSignIn(n.location.origin+f))})});"use strict";k.when("AudiblejQuery","ready").execute(function(a){a(".adbl_buybox_upsell_learn_more_link").click(function(){"undefined"!==typeof _satellite&&_satellite&&_satellite.track("learnMoreAboutMembershipClick")})});"use strict";k.when("AudiblejQuery","minervaBridgeUtil","ready").execute(function(a,b){a(".discovery-sign-in-to-listen-button").click(function(c){a(c.target);var f=
n.location.href;b&&b.launchAudiblePageAfterSignIn&&(c.preventDefault(),b.launchAudiblePageAfterSignIn(f))})});"use strict";k.when("AudiblejQuery","refMarkerCommonUtil","ready").execute(function(a,b){a(document).on("click",".adblPodcastEpisodesListButton",function(c){c=a(this).find("[data-asin]");digitalData.clickedAsin=c.data("asin");digitalData.clickedAsinContentType=c.data("content-type");a(".deviceType").val()&&b.sendRefMarker("_bb_view_all_ep_",a(".deviceType").val());"undefined"!==typeof _satellite&&
_satellite&&_satellite.track("adblBuyBoxViewAllEpisodes")})})});
/* ******** */
