(function(e){var f=window.AmazonUIPageJS||window.P,l=f._namespace||f.attributeErrors,k=l?l("AudibleWebNavigationAssets",""):f;k.guardFatal?k.guardFatal(e)(k,window):k.execute(function(){e(k,window)})})(function(e,f,l){function k(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}function p(a,b){if(!a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!b||"object"!==typeof b&&"function"!==typeof b?a:b}function w(a,b){if("function"!==
typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}var r=function(){return function(a,b){if(Array.isArray(a))return a;if(Symbol.iterator in Object(a)){var c=[],d=!0,m=!1,e=l;try{for(var h=a[Symbol.iterator](),g;!(d=(g=h.next()).done)&&(c.push(g.value),!b||c.length!==b);d=
!0);}catch(f){m=!0,e=f}finally{try{if(!d&&h["return"])h["return"]()}finally{if(m)throw e;}}return c}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}(),t="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},u=function(){function a(a,c){for(var d=0;d<c.length;d++){var m=c[d];m.enumerable=m.enumerable||!1;m.configurable=
!0;"value"in m&&(m.writable=!0);Object.defineProperty(a,m.key,m)}}return function(b,c,d){c&&a(b.prototype,c);d&&a(b,d);return b}}();e.when("cookieUtility","refMarkers","AddToHomeScreenPopover","navigatorHelper","ready").execute(function(a,b,c,d){d.cookieEnabled&&/iP(hone|od).+Version\/[\d\.]+.*Safari/i.test(d.userAgent)&&("standalone"in d&&d.standalone?b.buildAndPost("iOS_home_screen_app"):(b=document.getElementById("navigation-add-to-home-screen-popover"))&&!a.get("addToHomeScreenDismissed")&&(c=
new c(b),c.on("close",function(){var b=new Date;b.setMonth(b.getMonth()+6);a.set("addToHomeScreenDismissed","true",{expires:b})}),c.open()))});e.register("navigatorHelper",function(){return navigator});e.when("StrictEvents","accessibleClick").register("AddToHomeScreenPopover",function(a,b){return function(a){function d(a){k(this,d);var c=p(this,(d.__proto__||Object.getPrototypeOf(d)).call(this,["open","close"]));c.wrapperElement=a;(a=c.wrapperElement.getElementsByClassName("navigation-add-to-home-screen-popover-close-button")[0])&&
b.addEventListener(a,function(a){a.preventDefault();c.close()});return c}w(d,a);u(d,[{key:"open",value:function(){this.wrapperElement.classList.remove("bc-pub-hidden");this.emit("open")}},{key:"close",value:function(){this.wrapperElement.classList.add("bc-pub-hidden");this.emit("close")}}]);return d}(a)});e.when("ready").register("creditDataUtility",function(){var a=document.getElementById("audibleNavigation_creditInfo"),b=null;if(a&&(a=a&&a.getAttribute("data-json")))try{b=JSON.parse(a)}catch(c){"console"in
f&&"error"in console&&console.error("Error parsing credit info",c)}return{getCreditData:function(){return b&&Object.assign({},b)}}});e.when("cookieUtility","creditDataUtility","weblab.projectX").register("creditSummaryAutoOpenUtility",function(a,b,c){var d=new Date;d.setMonth(d.getMonth()+24);var e=(new Date).getTime(),f=!1,h=0;return{shouldAutoOpen:function(){if("T1"!==c||!navigator.cookieEnabled)return!1;var g=b.getCreditData();if(!g||!g.autoShowCreditInfo)return!1;h=parseInt(a.get("creditInfo_closeCount"));
if(isNaN(h))h=0;else if(4<=h)return!1;g=parseInt(a.get("creditInfo_lastVisitDate"));if(!isNaN(g)&&864E5>e-g)return a.set("creditInfo_lastVisitDate",e,{expires:d}),!1;a.set("creditInfo_lastVisitDate","",{expires:d});return f=!0},infoDismissed:function(){f&&(f=!1,h++,a.set("creditInfo_closeCount",h,{expires:d}),a.set("creditInfo_lastVisitDate",e,{expires:d}))}}});NodeList.prototype.forEach||(NodeList.prototype.forEach=Array.prototype.forEach);e.register("transitionUtility",function(){var a=void 0,b=
document.createElement("fakeelement"),c={transition:"transitionend",OTransition:"oTransitionEnd",MozTransition:"transitionend",WebkitTransition:"webkitTransitionEnd"},d;for(d in c)if(b.style[d]!==l){a=c[d];break}return{onTransitionEnd:function(b,d){if(a){var c=function(){var c=void 0,e=function(){return b.removeEventListener(a,c)},c=function(a){e();d()};b.addEventListener(a,c);return{v:e}}();if("object"===("undefined"===typeof c?"undefined":t(c)))return c.v}setTimeout(d);return function(){}}}});e.when("HeaderSlider",
"extraCreditAutoOpenUtility","creditSummaryAutoOpenUtility").register("creditSlider",function(a,b,c){var d=new a("#navigation-top-credits-wrapper",{offsetElementCssSelector:"#navigation-top-wrapper",toggleOnClickCssSelector:".navigation-top-credits-toggle",openOnClickCssSelector:".navigation-top-credits-open",closeOnClickCssSelector:".navigation-top-credits-close",onClose:function(){b.infoDismissed();c.infoDismissed()}});e.when("ready").execute(function(){(b.shouldAutoOpen()||c.shouldAutoOpen())&&
d.open()});return{toggle:function(){return d&&d.toggle()},open:function(){return d&&d.open()},close:function(){return d&&d.close()}}});e.when("ajax","creditDataUtility").register("extraCreditAutoOpenUtility",function(a,b){var c=!1;return{shouldAutoOpen:function(){var a=b.getCreditData();return a&&a.isEligibleToBuyExtraCredits&&!a.extraCreditsBannerDismissedRecently?c=!0:!1},infoDismissed:function(){if(c){c=!1;var b=document.getElementById("navigation-csrf-token");a({method:"POST",url:"/navigation/extracreditsbanner/dismiss",
body:b.name+"\x3d"+encodeURIComponent(b.value)})}}}});e.when("live","focus","boxUtility","transitionUtility").register("HeaderSlider",function(a,b,c,d){function f(){q&&q();var a=document.querySelector("#navigation-dimmer");a&&(a.style.display="block",setTimeout(function(){return a.classList.add("navigation-dimmer-show")}))}function l(){var a=document.querySelector("#navigation-dimmer");a&&(a.classList.remove("navigation-dimmer-show"),q=d.onTransitionEnd(a,function(){return a.style.display="none"}))}
function h(a,b){for(var c=a instanceof Array;b&&b!==document.body&&b!==document;){if(c?-1<a.indexOf(b):b===a)return!0;b=b.parentElement}return!1}var g=void 0;e.when("tray","mobile").execute(function(a){return g=a});var q=void 0,p={down:{side:"top",transform:"translateY",dimension:"height"},up:{side:"bottom",transform:"translateY",dimension:"height"},right:{side:"left",transform:"translateX",dimension:"width"},left:{side:"right",transform:"translateX",dimension:"width"}},n=void 0,v=function(){function e(b,
c){var d=this;k(this,e);if("string"!==typeof b)throw new TypeError("Invalid element css selector");c=c||{};if("object"!==("undefined"===typeof c?"undefined":t(c)))throw new TypeError("Invalid options object");c.direction=c.direction||"down";c.showDimmer=!1!==c.showDimmer;this.cssSelector=b;this.options=c;this.slideProps=p[c.direction];if(c.toggleOnClickCssSelector){a("click",c.toggleOnClickCssSelector,function(a){a.preventDefault();d.toggle(a)});b=document.querySelectorAll(c.toggleOnClickCssSelector);
for(var f=0;f<b.length;f++){var g=b[f];g.setAttribute("aria-haspopup",!0);g.setAttribute("aria-expanded",!1)}}c.openOnClickCssSelector&&a("click",c.openOnClickCssSelector,function(a){a.preventDefault();d.open()});c.closeOnClickCssSelector&&a("click",c.closeOnClickCssSelector,function(a){a.preventDefault();d.close()});document.addEventListener("focus",function(a){if(a.target&&d.isOpen()&&!h(d._getControlElements(),a.target)){var b=d._getSlider();b&&!h(b,a.target)&&d.close(!0)}},!0)}u(e,[{key:"focusIn",
value:function(){if(!this._focusIn){var a=this._getSlider();if(!a)return;var c=a.getAttribute("data-shift-focus-on-open");this._focusIn=b.change({focusElement:c&&document.getElementById(c)||a,isFocusOnLayer:!0})}this._focusIn()}},{key:"focusOut",value:function(){if(!this._focusOut){var a=this._getSlider();if(!a)return;this._focusOut=(a=(a=a.getAttribute("data-shift-focus-on-close"))&&document.getElementById(a))?b.change({focusElement:a}):function(){}}this._focusOut()}},{key:"open",value:function(a){var b=
this;e.closeCurrent(!0);a=this._getElements();var d=r(a,2);a=d[0];d=d[1];if(a&&!this.isOpen()){n=this;this.options.onOpen&&this.options.onOpen.call(this);for(var g=this._getTogglers(),h=0;h<g.length;h++){var k=g[h];k.classList.add("navigation-slider-toggler");k.classList.add("navigation-slider-toggler-is-open");k.setAttribute("aria-expanded","true")}this.closeOpenTrays();g=this._getOffset();a.classList.add("navigation-slider");a.style.visibility="hidden";a.style.display="block";var l=c.getBox(a)[this.slideProps.dimension];
a.style[this.slideProps.side]=g-l+"px";d.forEach(function(a){a.classList.add("navigation-slider-is-open");b._setTransform(a,b.slideProps.transform+"(0)");a.style.visibility="visible";a.classList.add("navigation-slider-direction-"+b.options.direction);setTimeout(function(){b.isOpen()&&b._setTransform(a,b.slideProps.transform+"("+l+"px)")})});this.options.showDimmer&&f();this.focusIn()}}},{key:"closeOpenTrays",value:function(){var a=document.getElementsByClassName("show-tray"),a=a&&0!==a.length?a[0]:
null;g&&a&&g.close(a)}},{key:"close",value:function(a){var b=this,c=this._getElements(),c=r(c,2),e=c[0],f=c[1];if(e&&this.isOpen()){n=null;this.options.onClose&&this.options.onClose.call(this);for(var c=this._getTogglers(),g=0;g<c.length;g++){var h=c[g];h.classList.remove("navigation-slider-toggler-is-open");h.setAttribute("aria-expanded","false")}this._getOffset();f.forEach(function(a){a.classList.remove("navigation-slider-is-open");b._setTransform(a,b.slideProps.transform+"(0)")});d.onTransitionEnd(e,
function(){b.isOpen()||(f.forEach(function(a){a.classList.remove("navigation-slider-direction-"+b.options.direction)}),e.style.display="none")});this.options.showDimmer&&l();a||this.focusOut()}}},{key:"isOpen",value:function(){return this===n}},{key:"toggle",value:function(a){this.isOpen()?this.close(a):this.open(a)}},{key:"_setTransform",value:function(a,b){a.style.mozTransform=a.style.msTransform=a.style.webkitTransform=a.style.transform=b}},{key:"_getOffset",value:function(){var a=this.options.offsetElementCssSelector&&
document.querySelector(this.options.offsetElementCssSelector);return a?c.getViewportOffset(a)[this.slideProps.side]+c.getBox(a)[this.slideProps.dimension]:0}},{key:"_getTogglers",value:function(){return this.options.toggleOnClickCssSelector&&document.querySelectorAll(this.options.toggleOnClickCssSelector)||[]}},{key:"_getControlElements",value:function(){return Array.prototype.slice.apply(document.querySelectorAll(this.options.toggleOnClickCssSelector+", "+this.options.openOnClickCssSelector+", "+
this.options.closeOnClickCssSelector))}},{key:"_getSlider",value:function(){return document.querySelector(this.cssSelector)}},{key:"_getElements",value:function(){var a=this._getSlider(),b=[];a&&(b.push(a),this.options.animationCompanionCssSelector&&b.push.apply(b,document.querySelectorAll(this.options.animationCompanionCssSelector)));return[a,b]}}],[{key:"closeCurrent",value:function(a){n&&n.close(a)}}]);return e}();["touchend","mouseup"].forEach(function(b){return a(b,"#navigation-dimmer",function(a){return v.closeCurrent()})});
return v});e.when("live").execute(function(a){a("change",".navigation-language-of-preference-picker",function(a){a=this.querySelector("select");f.location=a.value})});(function(){f.showSearch=function(){return e.when("searchSlider").execute(function(a){return a.toggle()})};f.showCredits=function(){return e.when("creditSlider").execute(function(a){return a.toggle()})};e.when("ready").execute(function(){if(f.external&&"notify"in f.external){var a=document.getElementById("navigation-app-notify-data");
if(a){var b=JSON.parse(a.getAttribute("data-json"));b&&b.credit_info&&f.external.notify(a.getAttribute("data-json"))}}})})();e.when("navigationLeft","searchSlider","ready").execute(function(){document.body.classList.add("navigation-initialized")});e.when("live","HeaderSlider").register("navigationLeft",function(a,b){var c=new b("#navigation-left-wrapper",{direction:"right",animationCompanionCssSelector:"#navigation-top-wrapper",toggleOnClickCssSelector:".navigation-left-toggle",openOnClickCssSelector:".navigation-left-open",
closeOnClickCssSelector:".navigation-left-close"});return{toggle:function(){return c.toggle()},open:function(){return c.open()},close:function(){return c.close()}}});e.when("live","HeaderSlider").register("searchSlider",function(a,b){var c=new b("#navigation-top-search-wrapper",{offsetElementCssSelector:"#navigation-top-wrapper",toggleOnClickCssSelector:".navigation-top-search-toggle",openOnClickCssSelector:".navigation-top-search-open",closeOnClickCssSelector:".navigation-top-search-close"});return{toggle:function(){return c.toggle()},
open:function(){return c.open()},close:function(){return c.close()}}});e.declare("weblab.projectX","C")});